import { ActividadEjecucion } from "./types";

export const ACTIVIDADES_INICIALES: ActividadEjecucion[] = [
  {
    id: "act-1",
    nombre: "Seguimiento al avance de trabajos de titulación",
    categoria: "POA",
    tipo: "obligatoria",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "02/09/2026",
    hasta: "18/09/2026",
    fechaLimiteExacta: "18/09/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg.", "Ing. Carlos López, Mg."],
    recursos: ["Matriz de seguimiento", "Almacenamiento institucional"],
    estado: "EN CURSO",
    medios: [
      {
        id: "m-1-1",
        nombre: "Informe",
        descripcion: "Informe técnico de avance de los proyectos de grado registrados.",
        estado: "CARGADA",
        archivoVigente: {
          nombre: "informe_seguimiento_titulacion.pdf",
          tamano: "2.4 MB",
          fechaCarga: "05/09/2026 — 14:32",
          cargadoPor: "Ing. Andrea Pérez, Mg.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "informe_seguimiento_titulacion.pdf",
            tamano: "2.4 MB",
            fechaCarga: "05/09/2026 — 14:32",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: true,
          },
        ],
      },
      {
        id: "m-1-2",
        nombre: "Acta",
        descripcion: "Acta de reunión con tutores y estudiantes asignados.",
        estado: "PENDIENTE",
        historialVersiones: [],
      },
    ],
  },
  {
    id: "act-2",
    nombre: "Jornada informativa para estudiantes",
    categoria: "Plan de Mejoras",
    tipo: "opcional",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "03/09/2026",
    hasta: "06/09/2026",
    fechaLimiteExacta: "06/09/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg."],
    recursos: ["Sala de reuniones", "Equipos de cómputo"],
    estado: "VENCIDA",
    medios: [
      {
        id: "m-2-1",
        nombre: "Certificado",
        descripcion: "Registro de asistencia y certificado de realización de la jornada.",
        estado: "PLAZO VENCIDO",
        historialVersiones: [],
      },
    ],
  },
  {
    id: "act-3",
    nombre: "Difusión de normativa interna de titulación",
    categoria: "Plan de Mejoras",
    tipo: "obligatoria",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "01/09/2026",
    hasta: "03/09/2026",
    fechaLimiteExacta: "03/09/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg."],
    recursos: ["Reglamento de titulación", "Correo institucional"],
    estado: "EVIDENCIAS COMPLETAS",
    medios: [
      {
        id: "m-3-1",
        nombre: "Informe",
        descripcion: "Constancia de difusión electrónica y reuniones informativas.",
        estado: "CARGADA",
        archivoVigente: {
          nombre: "informe_difusion_normativa.pdf",
          tamano: "1.5 MB",
          fechaCarga: "02/09/2026 — 10:15",
          cargadoPor: "Ing. Andrea Pérez, Mg.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "informe_difusion_normativa.pdf",
            tamano: "1.5 MB",
            fechaCarga: "02/09/2026 — 10:15",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: true,
          },
        ],
      },
    ],
  },
  {
    id: "act-4",
    nombre: "Revisión de planes de grado cohorte 2025",
    categoria: "POA",
    tipo: "obligatoria",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "15/08/2026",
    hasta: "28/08/2026",
    fechaLimiteExacta: "28/08/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg.", "Ing. Carlos López, Mg."],
    recursos: ["Sistema de gestión académica", "Rúbricas de evaluación"],
    estado: "EVIDENCIAS COMPLETAS",
    medios: [
      {
        id: "m-4-1",
        nombre: "Informe",
        descripcion: "Informe de aprobación de planes de titulación evaluados.",
        estado: "CARGADA",
        archivoVigente: {
          nombre: "informe_revision_planes_cohorte2025.pdf",
          tamano: "3.1 MB",
          fechaCarga: "27/08/2026 — 16:40",
          cargadoPor: "Ing. Andrea Pérez, Mg.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "informe_revision_planes_cohorte2025.pdf",
            tamano: "3.1 MB",
            fechaCarga: "27/08/2026 — 16:40",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: true,
          },
        ],
      },
      {
        id: "m-4-2",
        nombre: "Acta",
        descripcion: "Acta de sesión de comisión de titulación.",
        estado: "CARGADA",
        archivoVigente: {
          nombre: "acta_sesion_aprobacion_planes.pdf",
          tamano: "1.2 MB",
          fechaCarga: "28/08/2026 — 11:20",
          cargadoPor: "Ing. Carlos López, Mg.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "acta_sesion_aprobacion_planes.pdf",
            tamano: "1.2 MB",
            fechaCarga: "28/08/2026 — 11:20",
            cargadoPor: "Ing. Carlos López, Mg.",
            vigente: true,
          },
        ],
      },
    ],
  },
  {
    id: "act-5",
    nombre: "Actualización del repositorio de tesis",
    categoria: "POA",
    tipo: "opcional",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "10/08/2026",
    hasta: "25/08/2026",
    fechaLimiteExacta: "25/08/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg."],
    recursos: ["Almacenamiento institucional", "Servidor DSpace"],
    estado: "EVIDENCIAS COMPLETAS",
    medios: [
      {
        id: "m-5-1",
        nombre: "Informe",
        descripcion: "Reporte de carga y catalogación de tesis en el repositorio digital.",
        estado: "CARGADA",
        archivoVigente: {
          nombre: "reporte_repositorio_dspace.pdf",
          tamano: "1.8 MB",
          fechaCarga: "24/08/2026 — 09:15",
          cargadoPor: "Ing. Andrea Pérez, Mg.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "reporte_repositorio_dspace.pdf",
            tamano: "1.8 MB",
            fechaCarga: "24/08/2026 — 09:15",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: true,
          },
        ],
      },
    ],
  },
  {
    id: "act-6",
    nombre: "Taller de inducción metodológica para tutores",
    categoria: "Plan de Mejoras",
    tipo: "obligatoria",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "05/08/2026",
    hasta: "15/08/2026",
    fechaLimiteExacta: "15/08/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg."],
    recursos: ["Sala de conferencias", "Material didáctico"],
    estado: "EVIDENCIAS COMPLETAS",
    medios: [
      {
        id: "m-6-1",
        nombre: "Informe",
        descripcion: "Memoria del taller y consolidado de retroalimentación docente.",
        estado: "CARGADA",
        archivoVigente: {
          nombre: "memoria_taller_tutores.pdf",
          tamano: "2.1 MB",
          fechaCarga: "14/08/2026 — 17:00",
          cargadoPor: "Ing. Andrea Pérez, Mg.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "memoria_taller_tutores.pdf",
            tamano: "2.1 MB",
            fechaCarga: "14/08/2026 — 17:00",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: true,
          },
        ],
      },
      {
        id: "m-6-2",
        nombre: "Registro fotográfico",
        descripcion: "Evidencia visual del desarrollo del taller presencial.",
        estado: "CARGADA",
        archivoVigente: {
          nombre: "registro_fotografico_taller.pdf",
          tamano: "4.5 MB",
          fechaCarga: "15/08/2026 — 12:30",
          cargadoPor: "Ing. Andrea Pérez, Mg.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "registro_fotografico_taller.pdf",
            tamano: "4.5 MB",
            fechaCarga: "15/08/2026 — 12:30",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: true,
          },
        ],
      },
    ],
  },
  {
    id: "act-7",
    nombre: "Validación de rúbricas de evaluación final",
    categoria: "POA",
    tipo: "obligatoria",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "20/07/2026",
    hasta: "31/07/2026",
    fechaLimiteExacta: "31/07/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg.", "Ing. Carlos López, Mg."],
    recursos: ["Reglamento académico", "Matriz de competencias"],
    estado: "EVIDENCIAS COMPLETAS",
    medios: [
      {
        id: "m-7-1",
        nombre: "Resolución",
        descripcion: "Resolución interna de aprobación de las rúbricas evaluativas.",
        estado: "CARGADA",
        archivoVigente: {
          nombre: "resolucion_rubricas_titulacion.pdf",
          tamano: "950 KB",
          fechaCarga: "30/07/2026 — 15:45",
          cargadoPor: "Ing. Andrea Pérez, Mg.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "resolucion_rubricas_titulacion.pdf",
            tamano: "950 KB",
            fechaCarga: "30/07/2026 — 15:45",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: true,
          },
        ],
      },
    ],
  },
  {
    id: "act-8",
    nombre: "Elaboración de cronograma de defensas de titulación",
    categoria: "POA",
    tipo: "obligatoria",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "15/07/2026",
    hasta: "25/07/2026",
    fechaLimiteExacta: "25/07/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg."],
    recursos: ["Calendario académico FISEI", "Disponibilidad de aulas"],
    estado: "EVIDENCIAS COMPLETAS",
    medios: [
      {
        id: "m-8-1",
        nombre: "Oficio",
        descripcion: "Oficio circular de remisión de fechas de defensas a directores de carrera.",
        estado: "CARGADA",
        archivoVigente: {
          nombre: "oficio_cronograma_defensas.pdf",
          tamano: "780 KB",
          fechaCarga: "24/07/2026 — 11:10",
          cargadoPor: "Ing. Andrea Pérez, Mg.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "oficio_cronograma_defensas.pdf",
            tamano: "780 KB",
            fechaCarga: "24/07/2026 — 11:10",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: true,
          },
        ],
      },
    ],
  },
  {
    id: "act-9",
    nombre: "Seguimiento de procesos de graduación",
    categoria: "Acción de Mejora",
    tipo: "opcional",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "05/09/2026",
    hasta: "25/09/2026",
    fechaLimiteExacta: "25/09/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg.", "Ing. Carlos López, Mg."],
    recursos: ["Sistema de gestión académica", "Expedientes estudiantiles"],
    estado: "EN CURSO",
    medios: [
      {
        id: "m-9-1",
        nombre: "Informe",
        descripcion: "Estado de carpetas de titulación y prerrequisitos de graduación.",
        estado: "CARGADA",
        archivoVigente: {
          nombre: "informe_tramites_graduacion.pdf",
          tamano: "1.9 MB",
          fechaCarga: "06/09/2026 — 16:20",
          cargadoPor: "Ing. Carlos López, Mg.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "informe_tramites_graduacion.pdf",
            tamano: "1.9 MB",
            fechaCarga: "06/09/2026 — 16:20",
            cargadoPor: "Ing. Carlos López, Mg.",
            vigente: true,
          },
        ],
      },
      {
        id: "m-9-2",
        nombre: "Acta",
        descripcion: "Acta de validación de expedientes de titulación.",
        estado: "PENDIENTE",
        historialVersiones: [],
      },
    ],
  },
  {
    id: "act-10",
    nombre: "Consolidación del banco de reactivos",
    categoria: "POA",
    tipo: "opcional",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "20/09/2026",
    hasta: "10/10/2026",
    fechaLimiteExacta: "10/10/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg."],
    recursos: ["Banco de reactivos", "Plataforma Moodle UTA"],
    estado: "PENDIENTE",
    medios: [
      {
        id: "m-10-1",
        nombre: "Informe",
        descripcion: "Informe final de revisión y validación de reactivos del examen complexivo.",
        estado: "PENDIENTE",
        historialVersiones: [],
      },
    ],
  },
  {
    id: "act-11",
    nombre: "Revisión de documentación de titulación",
    categoria: "POA",
    tipo: "obligatoria",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "01/09/2026",
    hasta: "22/09/2026",
    fechaLimiteExacta: "22/09/2026 — 23:59",
    responsables: ["Ing. Carlos López, Mg."],
    recursos: ["Expedientes estudiantiles", "Reglamento de graduación"],
    estado: "PENDIENTE",
    medios: [
      {
        id: "m-11-1",
        nombre: "Informe",
        descripcion: "Informe técnico de revisión y validación de expedientes de grado.",
        estado: "PENDIENTE",
        historialVersiones: [],
      },
    ],
  },
];
