import {test,expect} from '@playwright/test';
import {reset,createPlan,completeMatrix,next,sign,documents,document,session,names,row,openReview,checklist,login} from './helpers';

test('Plan T1: elaboración, firma, observación persistente, devolución y ronda 2',async({page})=>{
 await reset(page);
 const others=await documents(page);
 const id=await createPlan(page);
 await completeMatrix(page,true);
 await expect(page.getByTestId('document-status')).toHaveText('BORRADOR');
 await expect(page.getByTestId('formal-version')).toHaveText('1.0');
 await expect(page.getByTestId('review-round')).toHaveText('Ronda 1');
 await expect(page.getByTestId('signature-count')).toHaveText('0 de 5');
 await expect(page.getByTestId('document-page')).toContainText('Formato Nº: UTA-SGC-A-2-1-P7-T1');
 await next(page);
 let d=await document(page,id);
 expect(d.currentArtifact.pageCount).toBe(d.currentArtifact.pages!.length);
 for(const a of d.currentArtifact.matriz!) {expect(a.responsableIds).toEqual(['usr-andrea-01','usr-carlos-02','usr-patricia-03']);expect(a.responsableNames).toEqual([names.andrea,names.carlos,names.patricia]);expect(a.responsablesEtiqueta).toBe('Responsable de la unidad');}
 await sign(page);
 d=await document(page,id);
 expect(d.documentState).toBe('EN REVISIÓN'); expect(d.currentArtifact.signatures).toHaveLength(1);
 const signed=structuredClone(d.currentArtifact);
 await expect(page.getByRole('button',{name:'ENVIAR A REVISIÓN',exact:true})).toHaveCount(0);
 d=await document(page,id);expect(d.documentState).toBe('EN REVISIÓN');expect(d.currentArtifact).toEqual(signed);
 await session(page,names.carlos);
 await expect(row(page,id)).toContainText('EN REVISIÓN');
 for(const draft of (await documents(page)).filter(d=>d.documentState==='BORRADOR')) await expect(row(page,draft.id)).toHaveCount(0);
 await openReview(page,id);
 await expect(page.getByTestId('document-page')).toHaveAttribute('data-artifact-id',signed.id);
 await expect(page.getByTestId('document-status')).toHaveText('EN REVISIÓN');
 await expect(page.getByTestId('signature-count')).toHaveText('1 de 5');
 const sigPage=signed.signatureSlots![0].pageNumber!;
 await page.getByRole('button',{name:String(sigPage),exact:true}).click();
 await expect(page.getByTestId('document-page')).toContainText(names.andrea);
 const approve=page.getByRole('button',{name:'Complete todos los aspectos a verificar.',exact:true});
 await expect(approve).toBeDisabled(); await expect(page.getByRole('status')).toHaveText('Complete todos los aspectos a verificar.');
 await checklist(page);
 await expect(page.getByRole('button',{name:'Aprobar y firmar',exact:true})).toBeEnabled();
 const matrixPage=signed.pages!.findIndex(p=>p.blocks?.some(b=>b.type==='matrix'))+1;
 await page.getByRole('button',{name:String(matrixPage),exact:true}).click();
 await page.getByRole('button',{name:`+ Agregar en pág. ${matrixPage}`,exact:true}).click();
 const observation='Observación E2E: corregir información de la matriz.';
 await page.getByPlaceholder('Detalle la inconsistencia o corrección que debe realizar el elaborador...').fill(observation);
 await page.getByRole('button',{name:'REGISTRAR OBSERVACIÓN',exact:true}).click();
 await expect(page.getByTestId('review-observation-count')).toHaveText('Observaciones (1)');
 await expect(page.getByRole('button',{name:'Existen observaciones activas.',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'1',exact:true}).click();
 await page.getByRole('button',{name:String(matrixPage),exact:true}).click();
 await expect(page.getByText(`"${observation}"`,{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'✕ Salir a Bandeja',exact:true}).click(); await openReview(page,id);
 await expect(page.getByTestId('review-observation-count')).toHaveText('Observaciones (1)');
 await page.reload(); await login(page); await session(page,names.carlos); await openReview(page,id);
 await expect(page.getByTestId('review-observation-count')).toHaveText('Observaciones (1)');
 d=await document(page,id); expect(d.observations[0]).toMatchObject({documentoId:id,artifactId:signed.id,ronda:1,formalVersion:'1.0',authorName:names.carlos,pagina:matrixPage});
 await page.getByRole('button',{name:'Devolver documento',exact:true}).click();
 await expect(page.getByText('Observaciones activas a remitir (1)',{exact:true})).toBeVisible();
 await page.getByPlaceholder('Indique las instrucciones de corrección para el docente...').fill('Corregir la información indicada en la matriz.');
 await page.getByRole('button',{name:'CONFIRMAR DEVOLUCIÓN',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Documento devuelto al elaborador'})).toBeVisible();
 await expect(page.getByRole('button',{name:'VOLVER A BANDEJA',exact:true})).toBeVisible();
 await expect(page.getByText(/CAMBIAR A ROL DOCENTE PARA CORREGIR/)).toHaveCount(0);
 d=await document(page,id);expect(d).toMatchObject({documentState:'EN CORRECCIÓN',formalVersion:'1.0',reviewRound:1,returnedByName:names.carlos});
 expect(d.artifactHistory[0]).toEqual(signed);
 await session(page,names.andrea);
 await expect(row(page,id)).toContainText('EN CORRECCIÓN');await expect(row(page,id)).toContainText('v1.0 (R1)');
 await row(page,id).getByRole('button',{name:'Continuar corrección',exact:true}).click();
 await page.getByText('Ver observaciones y resaltados del documento devuelto',{exact:true}).click();
 await expect(page.getByText(`"${observation}"`,{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Marcar como resuelta',exact:true}).click();
 await page.getByText('Ver observaciones y resaltados del documento devuelto',{exact:true}).click();
 await next(page);
 await page.getByPlaceholder('Defina el objetivo general...').fill('Gestionar y verificar los procesos de titulación con seguimiento periódico corregido.');
 await next(page);await next(page);await next(page);
 await page.getByRole('button',{name:'Continuar a Anexos →',exact:true}).click();await next(page);await next(page);
 d=await document(page,id);expect(d).toMatchObject({reviewRound:2,formalVersion:'1.0'});expect(d.currentArtifact.signatures).toHaveLength(0);expect(d.artifactHistory[0]).toEqual(signed);expect(d.observations[0].status).toBe('HISTORICAL');
 await sign(page);
 d=await document(page,id);expect(d).toMatchObject({documentState:'EN REVISIÓN',reviewRound:2});expect(d.currentArtifact.signatures).toHaveLength(1);
 expect((await documents(page)).filter(d=>d.id!==id)).toEqual(others);
});
