import { expect, test } from '@playwright/test';
import { completeMatrix, createPlan, document, next, openDocuments, reset } from './helpers';

test('T1 usa datos institucionales automáticos y registra actividades en una sola pantalla', async ({ page }) => {
  await reset(page);
  await openDocuments(page);
  await page.getByRole('button', { name: 'NUEVO DOCUMENTO', exact: true }).click();
  await page.getByRole('button', { name: 'CREAR PLAN DE TRABAJO', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Seleccionar grupo y período' });
  await expect(dialog.getByLabel('Período')).toHaveCount(0);
  await dialog.getByLabel('Grupo institucional').selectOption('grp-1');
  await dialog.getByRole('button', { name: 'Crear borrador', exact: true }).click();

  await expect(page.getByTestId('institutional-unit-select')).toBeDisabled();
  await expect(page.getByTestId('career-select')).toBeDisabled();
  await expect(page.locator('input.form-input[value="Julio – Diciembre 2026"]')).toBeDisabled();
  await next(page);
  const justification = page.getByRole('textbox', { name: 'Justificación', exact: true });
  await justification.fill('   ');
  await expect(page.getByText('Ingrese la justificación del Plan de Trabajo para continuar.', { exact: true })).toBeVisible();
  await justification.fill('Justificación validada para el Plan de Trabajo.');
  await page.getByPlaceholder('Defina el objetivo general...').fill('Gestionar el cumplimiento de las actividades institucionales.');
  await next(page);

  await expect(page.getByRole('heading', { name: 'Actividades', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Agregar actividad', exact: true }).click();
  const activityType = page.getByLabel('Tipo de actividad', { exact: true });
  await expect(activityType).toHaveValue('POA');
  await expect(page.getByText('Tipo: Otra', { exact: true })).toHaveCount(0);
  await activityType.selectOption('Plan de Mejoras');
  await expect(activityType).toHaveValue('Plan de Mejoras');
  await activityType.selectOption('Otra');
  await expect(activityType).toHaveValue('Otra');
  await activityType.selectOption('Acción de Mejora');
  await page.getByLabel('Actividad', { exact: true }).fill('Actividad integrada de validación');
  await page.getByLabel('Desde', { exact: true }).fill('2026-09-14');
  await page.getByLabel('Hasta', { exact: true }).fill('2026-12-18');
  await page.getByRole('checkbox', { name: 'Seleccionar todos', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Matriz de seguimiento', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Informe', exact: true }).check();
  await page.getByRole('button', { name: 'Guardar actividad', exact: true }).click();
  await expect(page.getByRole('row').filter({ hasText: 'Actividad integrada de validación' })).toContainText('Acción de Mejora');
});

test('Anexos acepta documentos no PDF y cancelar firma preserva el borrador', async ({ page }) => {
  await reset(page);
  await openDocuments(page);
  const id = await createPlan(page);
  await completeMatrix(page);
  await page.getByRole('button', { name: '← Anterior', exact: true }).click();
  await expect(page.getByRole('radio', { name: 'No', exact: true })).toBeVisible();
  await page.getByRole('radio', { name: 'No', exact: true }).check();
  await expect(page.locator('input[type=file]')).toHaveCount(0);
  await page.getByRole('radio', { name: 'Sí', exact: true }).check();
  await page.getByRole('button', { name: 'AGREGAR ANEXO', exact: true }).click();
  await page.locator('input[type=file]').setInputFiles({ name: 'cronograma.docx', mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', buffer: Buffer.from('demo') });
  await page.getByRole('button', { name: 'Agregar', exact: true }).click();
  await expect(page.getByText('cronograma.docx', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'AGREGAR ANEXO', exact: true }).click();
  await page.locator('input[type=file]').setInputFiles({ name: 'captura.png', mimeType: 'image/png', buffer: Buffer.from('demo') });
  await page.getByRole('button', { name: 'Agregar', exact: true }).click();
  await expect(page.getByText('captura.png', { exact: true })).toBeVisible();
  await next(page);
  await page.getByRole('button', { name: '← Anterior', exact: true }).click();
  await page.getByRole('button', { name: 'Eliminar' }).last().click();
  await expect(page.getByText('captura.png', { exact: true })).toHaveCount(0);
  await next(page);
  await next(page);
  await page.getByRole('button', { name: 'FIRMAR Y FINALIZAR ELABORACIÓN', exact: true }).click();
  const confirmation = page.getByRole('dialog', { name: 'Confirmar firma y finalización' });
  await expect(confirmation).toBeVisible();
  await confirmation.getByRole('button', { name: 'Cancelar', exact: true }).click();
  await expect(confirmation).toBeHidden();
  expect((await document(page, id)).currentArtifact.signatures).toHaveLength(0);
  await page.getByRole('button', { name: 'Volver a previsualización', exact: true }).click();
  await page.getByRole('button', { name: '← Anterior', exact: true }).click();
  await page.getByRole('button', { name: '← Anterior', exact: true }).click();
  await page.getByRole('button', { name: '← Anterior', exact: true }).click();
  await page.getByRole('textbox', { name: 'Justificación', exact: true }).fill('Justificación modificada después de cancelar la firma.');
});
