// Módulo 9 — Datos Mock de Reportes, Históricos y Cierre de Período
import {
  ReportePlanItem,
  PlanHistorico,
  PeriodoResumenCierre,
} from "./types";

// ─── PLANES ACTUALES PARA REPORTES (PERÍODO ACTIVO: JULIO – DICIEMBRE 2026) ───

export const REPORTES_PLANES_ACTUALES: ReportePlanItem[] = [
  {
    id: "rep-plan-1",
    nombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    docente: "Ing. Andrea Pérez, Mg.",
    periodo: "Julio – Diciembre 2026",
    version: "1.0",
    estado: "EN EJECUCIÓN",
    actividadesTotal: 10,
    actividadesCompletas: 7, // 7 de 10 actividades tienen todos sus medios cargados
    evidenciasRequeridas: 12,
    evidenciasCargadas: 10,
    evidenciasValidadas: 8,
    evidenciasObservadas: 1,
    evidenciasPendientes: 1,
    fechaElaboracion: "02/09/2026",
    actividades: [
      {
        id: "act-1",
        nombre: "Seguimiento al avance de trabajos de titulación",
        categoria: "POA",
        desde: "02/09/2026",
        hasta: "18/09/2026",
        mediosTotal: 2,
        mediosCargados: 2,
        mediosValidados: 1,
        mediosObservados: 1,
        mediosPendientes: 0,
        estadoDocumental: "OBSERVADA",
        observaciones: "Acta: falta firma de constancia de asistencia y sello del tutor.",
        observacionDetalle: {
          medio: "Acta",
          estado: "OBSERVADA",
          revisor: "Ing. Carlos López, Mg.",
          fecha: "07/09/2026 — 10:28",
          observacion: "Falta la firma de constancia de asistencia y sello del tutor.",
        },
      },
      {
        id: "act-2",
        nombre: "Jornada informativa para estudiantes",
        categoria: "Plan de Mejoras",
        desde: "03/09/2026",
        hasta: "06/09/2026",
        mediosTotal: 1,
        mediosCargados: 0,
        mediosValidados: 0,
        mediosObservados: 0,
        mediosPendientes: 1,
        estadoDocumental: "PENDIENTE DE CARGA",
      },
      {
        id: "act-3",
        nombre: "Difusión de normativa interna de titulación",
        categoria: "Plan de Mejoras",
        desde: "01/09/2026",
        hasta: "03/09/2026",
        mediosTotal: 1,
        mediosCargados: 1,
        mediosValidados: 1,
        mediosObservados: 0,
        mediosPendientes: 0,
        estadoDocumental: "EVIDENCIA VALIDADA",
      },
      {
        id: "act-4",
        nombre: "Revisión de planes de grado cohorte 2025",
        categoria: "POA",
        desde: "15/08/2026",
        hasta: "28/08/2026",
        mediosTotal: 2,
        mediosCargados: 2,
        mediosValidados: 2,
        mediosObservados: 0,
        mediosPendientes: 0,
        estadoDocumental: "EVIDENCIA VALIDADA",
      },
      {
        id: "act-5",
        nombre: "Actualización del repositorio de tesis",
        categoria: "POA",
        desde: "10/08/2026",
        hasta: "25/08/2026",
        mediosTotal: 1,
        mediosCargados: 1,
        mediosValidados: 1,
        mediosObservados: 0,
        mediosPendientes: 0,
        estadoDocumental: "EVIDENCIA VALIDADA",
      },
      {
        id: "act-6",
        nombre: "Taller de inducción metodológica para tutores",
        categoria: "Plan de Mejoras",
        desde: "05/08/2026",
        hasta: "15/08/2026",
        mediosTotal: 2,
        mediosCargados: 2,
        mediosValidados: 2,
        mediosObservados: 0,
        mediosPendientes: 0,
        estadoDocumental: "EVIDENCIA VALIDADA",
      },
      {
        id: "act-7",
        nombre: "Validación de rúbricas de evaluación final",
        categoria: "POA",
        desde: "20/07/2026",
        hasta: "31/07/2026",
        mediosTotal: 1,
        mediosCargados: 1,
        mediosValidados: 1,
        mediosObservados: 0,
        mediosPendientes: 0,
        estadoDocumental: "EVIDENCIA VALIDADA",
      },
      {
        id: "act-8",
        nombre: "Elaboración de cronograma de defensas de titulación",
        categoria: "POA",
        desde: "15/07/2026",
        hasta: "25/07/2026",
        mediosTotal: 1,
        mediosCargados: 1,
        mediosValidados: 1,
        mediosObservados: 0,
        mediosPendientes: 0,
        estadoDocumental: "EVIDENCIA VALIDADA",
      },
      {
        id: "act-9",
        nombre: "Seguimiento de procesos de graduación",
        categoria: "Acción de Mejora",
        desde: "05/09/2026",
        hasta: "25/09/2026",
        mediosTotal: 2,
        mediosCargados: 1,
        mediosValidados: 0,
        mediosObservados: 0,
        mediosPendientes: 1,
        estadoDocumental: "VALIDACIÓN PENDIENTE",
      },
      {
        id: "act-10",
        nombre: "Consolidación del banco de reactivos",
        categoria: "POA",
        desde: "20/09/2026",
        hasta: "10/10/2026",
        mediosTotal: 1,
        mediosCargados: 0,
        mediosValidados: 0,
        mediosObservados: 0,
        mediosPendientes: 1,
        estadoDocumental: "PENDIENTE DE CARGA",
      },
    ],
  },
  {
    id: "rep-plan-2",
    nombre: "Plan de Trabajo — Comisión de Eventos Académicos",
    grupo: "Comisión de Eventos Académicos",
    docente: "Ing. Andrea Pérez, Mg.",
    periodo: "Julio – Diciembre 2026",
    version: "1.0",
    estado: "EN CORRECCIÓN",
    actividadesTotal: 6,
    actividadesCompletas: 0,
    evidenciasRequeridas: 6,
    evidenciasCargadas: 0,
    evidenciasValidadas: 0,
    evidenciasObservadas: 0,
    evidenciasPendientes: 6,
    fechaElaboracion: "05/09/2026",
    actividades: [
      {
        id: "act-ev-1",
        nombre: "Organización de Semana Científica FISEI 2026",
        categoria: "POA",
        desde: "10/09/2026",
        hasta: "25/09/2026",
        mediosTotal: 1,
        mediosCargados: 0,
        mediosValidados: 0,
        mediosObservados: 0,
        mediosPendientes: 1,
        estadoDocumental: "PENDIENTE DE CARGA",
      },
      {
        id: "act-ev-2",
        nombre: "Ciclo de conferencias internacionales en IA",
        categoria: "POA",
        desde: "15/09/2026",
        hasta: "30/09/2026",
        mediosTotal: 1,
        mediosCargados: 0,
        mediosValidados: 0,
        mediosObservados: 0,
        mediosPendientes: 1,
        estadoDocumental: "PENDIENTE DE CARGA",
      },
    ],
  },
  {
    id: "rep-plan-3",
    nombre: "Plan de Trabajo — Comisión de Prácticas Preprofesionales",
    grupo: "Comisión de Prácticas Preprofesionales",
    docente: "Ing. Carlos López, Mg.",
    periodo: "Julio – Diciembre 2026",
    version: "1.0",
    estado: "EN EJECUCIÓN",
    actividadesTotal: 8,
    actividadesCompletas: 6,
    evidenciasRequeridas: 10,
    evidenciasCargadas: 8,
    evidenciasValidadas: 7,
    evidenciasObservadas: 1,
    evidenciasPendientes: 2,
    fechaElaboracion: "28/08/2026",
  },
  {
    id: "rep-plan-4",
    nombre: "Plan de Trabajo — Comisión de Investigación y Vinculación",
    grupo: "Comisión de Vinculación",
    docente: "Dr. Fernando Ramos, PhD.",
    periodo: "Julio – Diciembre 2026",
    version: "1.0",
    estado: "EN EJECUCIÓN",
    actividadesTotal: 7,
    actividadesCompletas: 5,
    evidenciasRequeridas: 9,
    evidenciasCargadas: 8,
    evidenciasValidadas: 8,
    evidenciasObservadas: 0,
    evidenciasPendientes: 1,
    fechaElaboracion: "20/08/2026",
  },
];

// ─── PLANES HISTÓRICOS (MODO SOLO LECTURA) ────────────────────────────────────

export const PLANES_HISTORICOS_DEMO: PlanHistorico[] = [
  // 1. Escenario de Andrea Pérez: Unidad de Titulación (Enero – Junio 2026 CERRADO)
  // Demuestra Versionamiento Formal (1.0 -> 2.0 por decisión institucional DEMO)
  {
    id: "hist-plan-1",
    codigo: "PLAN-2026-TIT-HIST",
    periodo: "Enero – Junio 2026",
    grupo: "Unidad de Titulación",
    nombreGrupo: "Unidad de Titulación",
    docente: "Ing. Andrea Pérez, Mg.",
    docenteNombre: "Ing. Andrea Pérez, Mg.",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    versionVigente: "2.0",
    versionFinal: "2.0",
    estadoFinal: "FINALIZADO",
    fechaElaboracion: "01/02/2026",
    fechaCierre: "25/07/2026",
    resolucionAprobacion: "Decisión institucional DEMO",
    actividadesTotal: 8,
    evidenciasRequeridas: 11,
    evidenciasCargadas: 11,
    evidenciasValidadas: 11,
    evidenciasObservadasHistoricas: 2,
    trazabilidadId: "plan-titulacion-historico",
    versiones: [
      {
        version: "1.0",
        fecha: "01/02/2026 — 10:15",
        origen: "Elaboración inicial",
        motivo: "Elaboración inicial.",
        descripcion: "Elaboración inicial",
      },
      {
        version: "2.0",
        fecha: "15/04/2026 — 16:30",
        origen: "Decisión institucional DEMO",
        resolucion: "Decisión institucional DEMO",
        motivo: "Modificación formal autorizada de la planificación del período.",
        descripcion: "Actualización formal del cronograma institucional",
        cambios: [
          {
            campo: "Cronograma de actividades",
            v1: "Planificación inicial.",
            v2: "Cronograma actualizado mediante modificación formal.",
          },
          {
            campo: "Recursos",
            v1: "Configuración inicial de recursos.",
            v2: "Recursos actualizados conforme a la modificación formal.",
          },
          {
            campo: "Medios de verificación",
            v1: "Configuración inicial.",
            v2: "Medios actualizados conforme a la modificación formal.",
          },
        ],
      },
    ],
    actividades: [
      {
        id: "h-act-1",
        numero: 1,
        nombre: "Acompañamiento a proyectos de titulación cohorte 2025-2",
        categoria: "POA",
        criterio: "100% de proyectos de titulación asignados cuentan con plan de tutorías",
        desde: "15/02/2026",
        hasta: "28/02/2026",
        estado: "CUMPLIDA",
        evidenciasRequeridas: 2,
        medios: [
          {
            id: "h-m-1",
            nombre: "Informe consolidado de avance de titulación",
            tipo: "Informe Técnico",
            version: "v1.0",
            archivoNombre: "informe_avance_titulacion_2026_1.pdf",
            archivoTamano: "2.2 MB",
            fechaCarga: "26/02/2026 — 16:15",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            estado: "VALIDADA",
            validadoPor: "Ing. Carlos López, Mg.",
            fechaValidacion: "28/02/2026 — 11:30",
          },
          {
            id: "h-m-2",
            nombre: "Acta de asesorías y registro de firmas",
            tipo: "Acta Firmada",
            version: "v2.0",
            archivoNombre: "acta_firmas_asesorias_firmada.pdf",
            archivoTamano: "1.9 MB",
            fechaCarga: "02/03/2026 — 09:20",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            estado: "VALIDADA",
            validadoPor: "Ing. Carlos López, Mg.",
            fechaValidacion: "03/03/2026 — 14:10",
            observacionesHistoricas: [
              {
                texto: "La versión 1.0 no incluía las firmas de los tutores asignados en el anexo B.",
                fechaHora: "28/02/2026 — 17:40",
                revisor: "Ing. Carlos López, Mg.",
                versionEvaluada: "v1.0",
              },
            ],
          },
        ],
      },
      {
        id: "h-act-2",
        numero: 2,
        nombre: "Jornadas de inducción al reglamento de titulación",
        categoria: "Plan de Mejoras",
        criterio: "Socialización de la normativa vigente con participación de estudiantes",
        desde: "01/03/2026",
        hasta: "10/03/2026",
        estado: "CUMPLIDA",
        evidenciasRequeridas: 1,
        medios: [
          {
            id: "h-m-3",
            nombre: "Memoria técnica de las jornadas",
            tipo: "Memoria Técnica",
            version: "v1.0",
            archivoNombre: "memoria_jornadas_titulacion_2026.pdf",
            archivoTamano: "3.1 MB",
            fechaCarga: "09/03/2026 — 18:00",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            estado: "VALIDADA",
            validadoPor: "Ing. Carlos López, Mg.",
            fechaValidacion: "10/03/2026 — 10:45",
          },
        ],
      },
      {
        id: "h-act-3",
        numero: 3,
        nombre: "Revisión documental de carpetas de titulación y defensas",
        categoria: "POA",
        criterio: "Expedientes completos conforme al reglamento de régimen académico",
        desde: "15/03/2026",
        hasta: "30/03/2026",
        estado: "CUMPLIDA",
        evidenciasRequeridas: 1,
        medios: [
          {
            id: "h-m-4",
            nombre: "Acta de verificación documental de defensas",
            tipo: "Acta Institucional",
            version: "v1.0",
            archivoNombre: "acta_verificacion_defensas_2026_1.pdf",
            archivoTamano: "1.7 MB",
            fechaCarga: "24/03/2026 — 15:30",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            estado: "VALIDADA",
            validadoPor: "Ing. Carlos López, Mg.",
            fechaValidacion: "26/03/2026 — 17:00",
          },
        ],
      },
      {
        id: "h-act-4",
        numero: 4,
        nombre: "Actualización de guías metodológicas de titulación",
        categoria: "POA",
        criterio: "Guías metodológicas actualizadas y aprobadas",
        desde: "01/04/2026",
        hasta: "20/04/2026",
        estado: "CUMPLIDA",
        evidenciasRequeridas: 1,
        medios: [
          {
            id: "h-m-5",
            nombre: "Guía metodológica de titulación actualizada",
            tipo: "Manual / Guía",
            version: "v1.0",
            archivoNombre: "guia_metodologica_titulacion_2026.pdf",
            archivoTamano: "2.8 MB",
            fechaCarga: "18/04/2026 — 11:20",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            estado: "VALIDADA",
            validadoPor: "Ing. Carlos López, Mg.",
            fechaValidacion: "20/04/2026 — 16:30",
          },
        ],
      },
      {
        id: "h-act-5",
        numero: 5,
        nombre: "Talleres de preparación complexiva — Fase I",
        categoria: "Plan de Mejoras",
        criterio: "Capacitación formativa para examen complexivo",
        desde: "25/04/2026",
        hasta: "10/05/2026",
        estado: "CUMPLIDA",
        evidenciasRequeridas: 1,
        medios: [
          {
            id: "h-m-6",
            nombre: "Registro de asistencia y contenidos del taller",
            tipo: "Registro Institucional",
            version: "v1.0",
            archivoNombre: "registro_asistencia_taller_complexivo.pdf",
            archivoTamano: "1.5 MB",
            fechaCarga: "08/05/2026 — 14:00",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            estado: "VALIDADA",
            validadoPor: "Ing. Carlos López, Mg.",
            fechaValidacion: "10/05/2026 — 10:15",
          },
        ],
      },
      {
        id: "h-act-6",
        numero: 6,
        nombre: "Talleres de preparación complexiva — Fase II y simulación",
        categoria: "Plan de Mejoras",
        criterio: "Cronograma actualizado según versión formal 2.0",
        desde: "10/05/2026",
        hasta: "30/05/2026",
        estado: "CUMPLIDA",
        evidenciasRequeridas: 2,
        medios: [
          {
            id: "h-m-7",
            nombre: "Informe técnico de ejecución de talleres complexivos",
            tipo: "Informe Técnico",
            version: "v2.0",
            archivoNombre: "informe_ejecucion_talleres_v2.pdf",
            archivoTamano: "2.5 MB",
            fechaCarga: "28/05/2026 — 16:30",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            estado: "VALIDADA",
            validadoPor: "Ing. Carlos López, Mg.",
            fechaValidacion: "30/05/2026 — 11:00",
          },
          {
            id: "h-m-8",
            nombre: "Registro biométrico de asistencia estudiantil",
            tipo: "Registro Digital",
            version: "v1.0",
            archivoNombre: "registro_biometrico_asistencia_fisei.pdf",
            archivoTamano: "1.2 MB",
            fechaCarga: "29/05/2026 — 17:45",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            estado: "VALIDADA",
            validadoPor: "Ing. Carlos López, Mg.",
            fechaValidacion: "30/05/2026 — 12:30",
          },
        ],
      },
      {
        id: "h-act-7",
        numero: 7,
        nombre: "Validación de reactivos para examen de grado complexivo",
        categoria: "POA",
        criterio: "Banco de reactivos auditado y aprobado",
        desde: "01/06/2026",
        hasta: "15/06/2026",
        estado: "CUMPLIDA",
        evidenciasRequeridas: 1,
        medios: [
          {
            id: "h-m-9",
            nombre: "Acta de validación del banco de reactivos",
            tipo: "Acta Confidencial",
            version: "v1.0",
            archivoNombre: "acta_validacion_banco_reactivos.pdf",
            archivoTamano: "1.4 MB",
            fechaCarga: "14/06/2026 — 12:00",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            estado: "VALIDADA",
            validadoPor: "Ing. Carlos López, Mg.",
            fechaValidacion: "15/06/2026 — 15:20",
          },
        ],
      },
      {
        id: "h-act-8",
        numero: 8,
        nombre: "Consolidación de actas finales de graduación y titulación",
        categoria: "POA",
        criterio: "Cierre formal de expedientes de grado del período",
        desde: "16/06/2026",
        hasta: "10/07/2026",
        estado: "CUMPLIDA",
        evidenciasRequeridas: 2,
        medios: [
          {
            id: "h-m-10",
            nombre: "Informe final de titulación del período Enero – Junio 2026",
            tipo: "Informe Final",
            version: "v1.0",
            archivoNombre: "informe_final_titulacion_2026_1.pdf",
            archivoTamano: "3.4 MB",
            fechaCarga: "08/07/2026 — 15:40",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            estado: "VALIDADA",
            validadoPor: "Ing. Carlos López, Mg.",
            fechaValidacion: "10/07/2026 — 16:30",
          },
          {
            id: "h-m-11",
            nombre: "Acta de cierre de expedientes y archivo digital",
            tipo: "Acta de Cierre",
            version: "v1.0",
            archivoNombre: "acta_cierre_expedientes_titulacion.pdf",
            archivoTamano: "2.1 MB",
            fechaCarga: "10/07/2026 — 18:00",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            estado: "VALIDADA",
            validadoPor: "Ing. Carlos López, Mg.",
            fechaValidacion: "12/07/2026 — 10:00",
          },
        ],
      },
    ],
    evidencias: [
      {
        id: "h-m-1",
        nombre: "Informe consolidado de avance de titulación",
        tipo: "Informe Técnico",
        version: "v1.0",
        archivoNombre: "informe_avance_titulacion_2026_1.pdf",
        archivoTamano: "2.2 MB",
        fechaCarga: "26/02/2026 — 16:15",
        cargadoPor: "Ing. Andrea Pérez, Mg.",
        estado: "VALIDADA",
        validadoPor: "Ing. Carlos López, Mg.",
        fechaValidacion: "28/02/2026 — 11:30",
      },
      {
        id: "h-m-2",
        nombre: "Acta de asesorías y registro de firmas",
        tipo: "Acta Firmada",
        version: "v2.0",
        archivoNombre: "acta_firmas_asesorias_firmada.pdf",
        archivoTamano: "1.9 MB",
        fechaCarga: "02/03/2026 — 09:20",
        cargadoPor: "Ing. Andrea Pérez, Mg.",
        estado: "VALIDADA",
        validadoPor: "Ing. Carlos López, Mg.",
        fechaValidacion: "03/03/2026 — 14:10",
      },
      {
        id: "h-m-3",
        nombre: "Memoria técnica de las jornadas",
        tipo: "Memoria Técnica",
        version: "v1.0",
        archivoNombre: "memoria_jornadas_titulacion_2026.pdf",
        archivoTamano: "3.1 MB",
        fechaCarga: "09/03/2026 — 18:00",
        cargadoPor: "Ing. Andrea Pérez, Mg.",
        estado: "VALIDADA",
        validadoPor: "Ing. Carlos López, Mg.",
        fechaValidacion: "10/03/2026 — 10:45",
      },
      {
        id: "h-m-4",
        nombre: "Acta de verificación documental de defensas",
        tipo: "Acta Institucional",
        version: "v1.0",
        archivoNombre: "acta_verificacion_defensas_2026_1.pdf",
        archivoTamano: "1.7 MB",
        fechaCarga: "24/03/2026 — 15:30",
        cargadoPor: "Ing. Andrea Pérez, Mg.",
        estado: "VALIDADA",
        validadoPor: "Ing. Carlos López, Mg.",
        fechaValidacion: "26/03/2026 — 17:00",
      },
      {
        id: "h-m-5",
        nombre: "Guía metodológica de titulación actualizada",
        tipo: "Manual / Guía",
        version: "v1.0",
        archivoNombre: "guia_metodologica_titulacion_2026.pdf",
        archivoTamano: "2.8 MB",
        fechaCarga: "18/04/2026 — 11:20",
        cargadoPor: "Ing. Andrea Pérez, Mg.",
        estado: "VALIDADA",
        validadoPor: "Ing. Carlos López, Mg.",
        fechaValidacion: "20/04/2026 — 16:30",
      },
      {
        id: "h-m-6",
        nombre: "Registro de asistencia y contenidos del taller",
        tipo: "Registro Institucional",
        version: "v1.0",
        archivoNombre: "registro_asistencia_taller_complexivo.pdf",
        archivoTamano: "1.5 MB",
        fechaCarga: "08/05/2026 — 14:00",
        cargadoPor: "Ing. Andrea Pérez, Mg.",
        estado: "VALIDADA",
        validadoPor: "Ing. Carlos López, Mg.",
        fechaValidacion: "10/05/2026 — 10:15",
      },
      {
        id: "h-m-7",
        nombre: "Informe técnico de ejecución de talleres complexivos",
        tipo: "Informe Técnico",
        version: "v2.0",
        archivoNombre: "informe_ejecucion_talleres_v2.pdf",
        archivoTamano: "2.5 MB",
        fechaCarga: "28/05/2026 — 16:30",
        cargadoPor: "Ing. Andrea Pérez, Mg.",
        estado: "VALIDADA",
        validadoPor: "Ing. Carlos López, Mg.",
        fechaValidacion: "30/05/2026 — 11:00",
      },
      {
        id: "h-m-8",
        nombre: "Registro biométrico de asistencia estudiantil",
        tipo: "Registro Digital",
        version: "v1.0",
        archivoNombre: "registro_biometrico_asistencia_fisei.pdf",
        archivoTamano: "1.2 MB",
        fechaCarga: "29/05/2026 — 17:45",
        cargadoPor: "Ing. Andrea Pérez, Mg.",
        estado: "VALIDADA",
        validadoPor: "Ing. Carlos López, Mg.",
        fechaValidacion: "30/05/2026 — 12:30",
      },
      {
        id: "h-m-9",
        nombre: "Acta de validación del banco de reactivos",
        tipo: "Acta Confidencial",
        version: "v1.0",
        archivoNombre: "acta_validacion_banco_reactivos.pdf",
        archivoTamano: "1.4 MB",
        fechaCarga: "14/06/2026 — 12:00",
        cargadoPor: "Ing. Andrea Pérez, Mg.",
        estado: "VALIDADA",
        validadoPor: "Ing. Carlos López, Mg.",
        fechaValidacion: "15/06/2026 — 15:20",
      },
      {
        id: "h-m-10",
        nombre: "Informe final de titulación del período Enero – Junio 2026",
        tipo: "Informe Final",
        version: "v1.0",
        archivoNombre: "informe_final_titulacion_2026_1.pdf",
        archivoTamano: "3.4 MB",
        fechaCarga: "08/07/2026 — 15:40",
        cargadoPor: "Ing. Andrea Pérez, Mg.",
        estado: "VALIDADA",
        validadoPor: "Ing. Carlos López, Mg.",
        fechaValidacion: "10/07/2026 — 16:30",
      },
      {
        id: "h-m-11",
        nombre: "Acta de cierre de expedientes y archivo digital",
        tipo: "Acta de Cierre",
        version: "v1.0",
        archivoNombre: "acta_cierre_expedientes_titulacion.pdf",
        archivoTamano: "2.1 MB",
        fechaCarga: "10/07/2026 — 18:00",
        cargadoPor: "Ing. Andrea Pérez, Mg.",
        estado: "VALIDADA",
        validadoPor: "Ing. Carlos López, Mg.",
        fechaValidacion: "12/07/2026 — 10:00",
      },
    ],
  },

  // 2. Escenario de Carlos López: Comisión de Eventos Académicos (Enero – Junio 2026 CERRADO)
  {
    id: "hist-plan-2",
    codigo: "PLAN-2026-EVE-HIST",
    periodo: "Enero – Junio 2026",
    grupo: "Comisión de Eventos Académicos",
    nombreGrupo: "Comisión de Eventos Académicos",
    docente: "Ing. Carlos López, Mg.",
    docenteNombre: "Ing. Carlos López, Mg.",
    planNombre: "Plan de Trabajo — Comisión de Eventos Académicos",
    versionVigente: "1.0",
    versionFinal: "1.0",
    estadoFinal: "FINALIZADO",
    fechaElaboracion: "05/02/2026",
    fechaCierre: "25/07/2026",
    resolucionAprobacion: "Decisión institucional DEMO",
    actividadesTotal: 6,
    evidenciasRequeridas: 8,
    evidenciasValidadas: 8,
    evidenciasObservadasHistoricas: 1,
    versiones: [
      {
        version: "1.0",
        fecha: "05/02/2026 — 09:00",
        origen: "Elaboración inicial formal",
        descripcion: "Versión aprobada y ejecutada durante el ciclo académico.",
      },
    ],
    actividades: [
      {
        id: "h-eve-act-1",
        numero: 1,
        nombre: "Organización de la Semana Científica y Tecnológica FISEI 2026",
        categoria: "POA",
        criterio: "Planificación de conferencias, cronograma y ponentes invitados",
        desde: "10/02/2026",
        hasta: "28/02/2026",
        estado: "CUMPLIDA",
        evidenciasRequeridas: 2,
        medios: [
          {
            id: "h-eve-m-1",
            nombre: "Programa oficial y memoria técnica de ponencias",
            tipo: "Memoria Técnica",
            version: "v1.0",
            archivoNombre: "programa_semana_cientifica_fisei_2026.pdf",
            archivoTamano: "1.8 MB",
            fechaCarga: "25/02/2026 — 11:40",
            cargadoPor: "Ing. Carlos López, Mg.",
            estado: "VALIDADA",
            validadoPor: "Ing. Laura Medina, Mg.",
            fechaValidacion: "27/02/2026 — 16:30",
          },
        ],
      },
      {
        id: "h-eve-act-2",
        numero: 2,
        nombre: "Coordinación de talleres y registro de participación docente",
        categoria: "POA",
        criterio: "Registro de asistencia y actas de participación académica",
        desde: "01/04/2026",
        hasta: "15/06/2026",
        estado: "CUMPLIDA",
        evidenciasRequeridas: 2,
        medios: [
          {
            id: "h-eve-m-2",
            nombre: "Acta consolidada de participación y certificados emitidos",
            tipo: "Acta Institucional",
            version: "v1.0",
            archivoNombre: "acta_participacion_eventos_fisei.pdf",
            archivoTamano: "2.4 MB",
            fechaCarga: "12/06/2026 — 14:15",
            cargadoPor: "Ing. Carlos López, Mg.",
            estado: "VALIDADA",
            validadoPor: "Ing. Laura Medina, Mg.",
            fechaValidacion: "15/06/2026 — 09:45",
          },
        ],
      },
    ],
    evidencias: [
      {
        id: "h-eve-m-1",
        nombre: "Programa oficial y memoria técnica de ponencias",
        tipo: "Memoria Técnica",
        version: "v1.0",
        archivoNombre: "programa_semana_cientifica_fisei_2026.pdf",
        archivoTamano: "1.8 MB",
        fechaCarga: "25/02/2026 — 11:40",
        cargadoPor: "Ing. Carlos López, Mg.",
        estado: "VALIDADA",
        validadoPor: "Ing. Laura Medina, Mg.",
        fechaValidacion: "27/02/2026 — 16:30",
      },
      {
        id: "h-eve-m-2",
        nombre: "Acta consolidada de participación y certificados emitidos",
        tipo: "Acta Institucional",
        version: "v1.0",
        archivoNombre: "acta_participacion_eventos_fisei.pdf",
        archivoTamano: "2.4 MB",
        fechaCarga: "12/06/2026 — 14:15",
        cargadoPor: "Ing. Carlos López, Mg.",
        estado: "VALIDADA",
        validadoPor: "Ing. Laura Medina, Mg.",
        fechaValidacion: "15/06/2026 — 09:45",
      },
    ],
  },

  // 3. Escenario de Andrea Pérez: Vinculación con la Sociedad (Enero – Junio 2026 CERRADO)
  {
    id: "hist-plan-4",
    codigo: "PLAN-2026-VINC-HIST",
    periodo: "Enero – Junio 2026",
    grupo: "Comisión de Vinculación con la Sociedad",
    nombreGrupo: "Comisión de Vinculación con la Sociedad",
    docente: "Ing. Andrea Pérez, Mg.",
    docenteNombre: "Ing. Andrea Pérez, Mg.",
    planNombre: "Plan de Trabajo — Comisión de Vinculación con la Sociedad",
    versionVigente: "1.0",
    versionFinal: "1.0",
    estadoFinal: "FINALIZADO",
    fechaElaboracion: "10/02/2026",
    fechaCierre: "25/07/2026",
    resolucionAprobacion: "Decisión institucional DEMO",
    actividadesTotal: 5,
    evidenciasRequeridas: 6,
    evidenciasValidadas: 6,
    evidenciasObservadasHistoricas: 0,
    versiones: [
      {
        version: "1.0",
        fecha: "10/02/2026 — 08:30",
        origen: "Elaboración inicial formal",
        descripcion: "Plan de vinculación social aprobado para el período.",
      },
    ],
    actividades: [
      {
        id: "h-vinc-act-1",
        numero: 1,
        nombre: "Talleres de alfabetización digital comunitaria",
        categoria: "POA",
        criterio: "Capacitación a sectores vulnerables de la provincia de Tungurahua",
        desde: "01/03/2026",
        hasta: "15/05/2026",
        estado: "CUMPLIDA",
        evidenciasRequeridas: 2,
        medios: [
          {
            id: "h-vinc-m-1",
            nombre: "Registro fotográfico y listas de asistencia",
            tipo: "Registro Técnico",
            version: "v1.0",
            archivoNombre: "asistencia_talleres_vinculacion_2026.pdf",
            archivoTamano: "3.4 MB",
            fechaCarga: "14/05/2026 — 17:00",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            estado: "VALIDADA",
            validadoPor: "Ing. Carlos López, Mg.",
            fechaValidacion: "18/05/2026 — 10:15",
          },
        ],
      },
    ],
    evidencias: [
      {
        id: "h-vinc-m-1",
        nombre: "Registro fotográfico y listas de asistencia",
        tipo: "Registro Técnico",
        version: "v1.0",
        archivoNombre: "asistencia_talleres_vinculacion_2026.pdf",
        archivoTamano: "3.4 MB",
        fechaCarga: "14/05/2026 — 17:00",
        cargadoPor: "Ing. Andrea Pérez, Mg.",
        estado: "VALIDADA",
        validadoPor: "Ing. Carlos López, Mg.",
        fechaValidacion: "18/05/2026 — 10:15",
      },
    ],
  },

  // 4. Período Anterior: Julio – Diciembre 2025 CERRADO
  {
    id: "hist-plan-3",
    codigo: "PLAN-2025-TIT-HIST",
    periodo: "Julio – Diciembre 2025",
    grupo: "Unidad de Titulación",
    nombreGrupo: "Unidad de Titulación",
    docente: "Ing. Andrea Pérez, Mg.",
    docenteNombre: "Ing. Andrea Pérez, Mg.",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    versionVigente: "1.0",
    versionFinal: "1.0",
    estadoFinal: "FINALIZADO",
    fechaElaboracion: "15/07/2025",
    fechaCierre: "20/01/2026",
    resolucionAprobacion: "Decisión institucional DEMO",
    actividadesTotal: 7,
    evidenciasRequeridas: 9,
    evidenciasValidadas: 9,
    evidenciasObservadasHistoricas: 0,
    versiones: [
      {
        version: "1.0",
        fecha: "15/07/2025 — 11:30",
        origen: "Elaboración inicial formal",
        descripcion: "Plan institucional cerrado con registro documental completo.",
      },
    ],
    actividades: [
      {
        id: "h-2025-act-1",
        numero: 1,
        nombre: "Procesos de graduación cohorte 2025-1",
        categoria: "POA",
        criterio: "Sustentación de trabajos de integración curricular",
        desde: "01/08/2025",
        hasta: "15/12/2025",
        estado: "CUMPLIDA",
        evidenciasRequeridas: 2,
        medios: [
          {
            id: "h-2025-m-1",
            nombre: "Informe final de titulación período 2025",
            tipo: "Informe Anual",
            version: "v1.0",
            archivoNombre: "informe_anual_titulacion_2025.pdf",
            archivoTamano: "2.5 MB",
            fechaCarga: "18/12/2025 — 16:20",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            estado: "VALIDADA",
            validadoPor: "Ing. Carlos López, Mg.",
            fechaValidacion: "20/12/2025 — 11:00",
          },
        ],
      },
    ],
    evidencias: [
      {
        id: "h-2025-m-1",
        nombre: "Informe final de titulación período 2025",
        tipo: "Informe Anual",
        version: "v1.0",
        archivoNombre: "informe_anual_titulacion_2025.pdf",
        archivoTamano: "2.5 MB",
        fechaCarga: "18/12/2025 — 16:20",
        cargadoPor: "Ing. Andrea Pérez, Mg.",
        estado: "VALIDADA",
        validadoPor: "Ing. Carlos López, Mg.",
        fechaValidacion: "20/12/2025 — 11:00",
      },
    ],
  },
];

// ─── RESUMEN DE PERÍODOS Y CIERRE ADMINISTRATIVO ─────────────────────────────

export const PERIODOS_INICIALES: PeriodoResumenCierre[] = [
  {
    id: "per-1",
    nombre: "Julio – Diciembre 2026",
    estado: "ACTIVO",
    planesTotal: 4,
    planesFinalizados: 3,
    planesEnEjecucion: 1,
    actividadesTotal: 31,
    evidenciasRequeridas: 37,
    evidenciasCargadas: 26,
    evidenciasValidadas: 23,
    evidenciasObservadas: 1,
    evidenciasPendientes: 2,
  },
  {
    id: "per-2",
    nombre: "Enero – Junio 2026",
    estado: "CERRADO",
    planesTotal: 4,
    planesFinalizados: 4,
    planesEnEjecucion: 0,
    actividadesTotal: 32,
    evidenciasRequeridas: 41,
    evidenciasCargadas: 41,
    evidenciasValidadas: 39,
    evidenciasObservadas: 6, // Observadas históricas en trazabilidad
    evidenciasPendientes: 0,
    fechaCierre: "25/07/2026 — 18:00",
    cerradoPor: "Ing. Laura Medina, Mg.",
  },
  {
    id: "per-3",
    nombre: "Julio – Diciembre 2025",
    estado: "CERRADO",
    planesTotal: 4,
    planesFinalizados: 4,
    planesEnEjecucion: 0,
    actividadesTotal: 28,
    evidenciasRequeridas: 35,
    evidenciasCargadas: 35,
    evidenciasValidadas: 35,
    evidenciasObservadas: 2,
    evidenciasPendientes: 0,
    fechaCierre: "20/01/2026 — 17:30",
    cerradoPor: "Ing. Laura Medina, Mg.",
  },
];
