// ─── Mock Data inicial para el Motor Documental FISEI ─────────────────────────
import { ActividadMatrizDoc, ActividadInformeDoc, DocumentArtifact, DocumentMasterState, FlowStageNode } from "./types";

export const FECHA_SISTEMA = "07/09/2026";

export const MATRIZ_INICIAL_DOC: ActividadMatrizDoc[] = [
  {
    id: 1,
    nombre: "Elaboración de cronograma de eventos académicos del período",
    desde: "08/09/2026",
    hasta: "20/09/2026",
    responsables: ["Ing. Andrea Pérez, Mg."],
    recursos: ["Laboratorios FISEI", "Plataforma Virtual UTA"],
    medios: ["Cronograma oficial aprobado en PDF"],
  },
  {
    id: 2,
    nombre: "Coordinación y gestión de ponentes para conferencias magistrales",
    desde: "21/09/2026",
    hasta: "15/10/2026",
    responsables: ["Ing. Andrea Pérez, Mg."],
    recursos: ["Auditorio FISEI", "Equipo audiovisual"],
    medios: ["Cartas de invitación y confirmación de ponentes"],
  },
  {
    id: 3,
    nombre: "Revisión técnica de proyectos de grado para jornada científica",
    desde: "16/10/2026",
    hasta: "05/11/2026",
    responsables: ["Ing. Andrea Pérez, Mg.", "Ing. Carlos López, Mg."],
    recursos: ["Aulas de posgrado", "Repositorio digital"],
    medios: ["Actas de evaluación de proyectos"],
  },
  {
    id: 4,
    nombre: "Ejecución de la Semana Técnica de Software e Innovación",
    desde: "06/11/2026",
    hasta: "20/11/2026",
    responsables: ["Ing. Andrea Pérez, Mg."],
    recursos: ["Campus Huachi", "Salas de cómputo"],
    medios: ["Registro de asistencia y fotografías del evento"],
  },
  {
    id: 5,
    nombre: "Informe final de resultados y evaluación de eventos del período",
    desde: "21/11/2026",
    hasta: "15/12/2026",
    responsables: ["Ing. Andrea Pérez, Mg."],
    recursos: ["Sistema de Gestión FISEI"],
    medios: ["Informe final de actividades firmado electrónicamente"],
  },
];

export const JUSTIFICACION_INICIAL =
  "La Comisión de Eventos Académicos de la FISEI desarrolla actividades orientadas al fortalecimiento del intercambio científico, actualización tecnológica y vinculación académica de estudiantes y docentes. Durante el período Julio – Diciembre 2026 se requiere coordinar eventos institucionales de impacto, conferencias magistrales y la Semana Técnica de Software para responder a los estándares de acreditación y calidad educativa de la Universidad Técnica de Ambato.";

export const OBJETIVO_INICIAL =
  "Planificar, coordinar y ejecutar los eventos académicos y científicos de la FISEI durante el período Julio – Diciembre 2026, asegurando la participación de ponentes calificados y el cumplimiento de los cronogramas institucionales aprobados.";

export const FLOW_STAGES_INICIAL: FlowStageNode[] = [
  {
    id: "stage-1",
    actorId: "usr-andrea-01",
    stageName: "ETAPA 1 — Elaboración",
    actorName: "Ing. Andrea Pérez, Mg.",
    actorCargo: "Docente elaborador",
    actorRole: "docente",
    estado: "PENDIENTE",
  },
  {
    id: "stage-2",
    actorId: "usr-carlos-02",
    stageName: "ETAPA 2 — Revisión",
    subLevelName: "Nivel 1 — Revisión técnica",
    actorName: "Ing. Carlos López, Mg.",
    actorCargo: "Responsable de revisión técnica",
    actorRole: "revisor",
    estado: "PENDIENTE",
  },
  {
    id: "stage-3",
    actorId: "usr-patricia-03",
    stageName: "ETAPA 3 — Validación final",
    subLevelName: "Validación y Aprobación",
    actorName: "Ing. Patricia Salazar, Mg.",
    actorCargo: "Coordinadora de Unidad",
    actorRole: "validador",
    estado: "PENDIENTE",
  },
];

export const CARRERAS_USUARIO_ANDREA = [
  "Ingeniería de Software",
  "Tecnologías de la Información",
];

export const ACTIVIDADES_INFORME_TITULACION_INICIAL: ActividadInformeDoc[] = [
  {
    id: 1,
    actividad: "Seguimiento al avance de trabajos de titulación",
    mediosVerificacion: "Reporte de seguimiento",
    porcentajeEjecucion: 100,
    observaciones: "Seguimiento completado en las fechas establecidas.",
  },
  {
    id: 2,
    actividad: "Jornada informativa para estudiantes",
    mediosVerificacion: "Registro de asistencia",
    porcentajeEjecucion: 100,
    observaciones: "Alta participación estudiantil, se cubrieron todas las dudas.",
  },
  {
    id: 3,
    actividad: "Difusión de normativa interna de titulación",
    mediosVerificacion: "Capturas de difusión",
    porcentajeEjecucion: 100,
    observaciones: "Normativa difundida por canales oficiales.",
  },
  {
    id: 4,
    actividad: "Revisión de planes de grado cohorte 2025",
    mediosVerificacion: "Actas de revisión",
    porcentajeEjecucion: 85,
    observaciones: "En proceso de ajustes finales por parte de estudiantes.",
  },
  {
    id: 5,
    actividad: "Taller de inducción metodológica para tutores",
    mediosVerificacion: "Registro de asistencia",
    porcentajeEjecucion: 100,
    observaciones: "Taller ejecutado con éxito.",
  },
];

export const INITIAL_ARTIFACT: DocumentArtifact = {
  id: "art-plan-fisei-v1-r1",
  documentType: "PLAN_TRABAJO",
  codigoFormatoOficial: "UTA-SGC-A-2-1-P7-T1",
  titulo: "Plan de Trabajo: Comisión de Eventos Académicos",
  formalVersion: "1.0",
  reviewRound: 1,
  get pageCount() { return this.pages?.length ?? 0; },
  generatedAt: "07/09/2026 09:15",
  generatedBy: "Ing. Andrea Pérez, Mg.",
  grupo: "Comisión de Eventos Académicos",
  carrera: "Ingeniería de Software",
  periodo: "Julio – Diciembre 2026",
  unidadAcademica: "Facultad de Ingeniería en Sistemas, Electrónica e Industrial",
  elaborador: {
    id: "usr-andrea-01",
    nombre: "Ing. Andrea Pérez, Mg.",
    cargo: "Docente elaborador",
    email: "andrea.perez@uta.edu.ec",
  },
  justificacion: JUSTIFICACION_INICIAL,
  objetivo: OBJETIVO_INICIAL,
  matriz: MATRIZ_INICIAL_DOC,
  tieneAnexos: "si",
  anexos: [
    {
      id: 1,
      nombre: "Propuesta temática y cronograma detallado de ponencias",
      archivo: "cronograma_detallado_2026.pdf",
      tamano: "1.2 MB",
    },
  ],
  signatures: [],
  historialCambios: [
    {
      version: "1.0",
      descripcion: "Elaboración del Plan de Trabajo",
      fecha: "05/09/2026",
    },
  ],
};

export const OBSERVACIONES_INICIALES_EVENTOS = [
  {
    id: 1,
    documentoId: "doc-plan-eventos-2026",
    artifactId: "art-plan-fisei-v1-r1",
    formalVersion: "1.0",
    ronda: 1,
    pagina: 2,
    pageIndex: 1,
    pageNumber: 2,
    revisor: "Ing. Carlos López, Mg.",
    cargo: "Responsable de revisión técnica",
    fecha: "06/09/2026 11:20",
    authorUserId: "usr-carlos-02",
    authorName: "Ing. Carlos López, Mg.",
    createdAt: "06/09/2026 11:20",
    texto: "Ajustar el cronograma y recursos en la sección de ponencias magistrales para evitar solapamiento con exámenes.",
    estado: "activa" as const,
    status: "ACTIVE" as const,
    tipo: "seccion" as const,
    seccion: "Actividad 2 — Coordinación de ponentes",
  },
  {
    id: 2,
    documentoId: "doc-plan-eventos-2026",
    artifactId: "art-plan-fisei-v1-r1",
    formalVersion: "1.0",
    ronda: 1,
    pagina: 3,
    pageIndex: 2,
    pageNumber: 3,
    revisor: "Ing. Carlos López, Mg.",
    cargo: "Responsable de revisión técnica",
    fecha: "06/09/2026 11:25",
    authorUserId: "usr-carlos-02",
    authorName: "Ing. Carlos López, Mg.",
    createdAt: "06/09/2026 11:25",
    texto: "Especificar medios de verificación definitivos para la Semana Técnica antes de reenviar.",
    estado: "activa" as const,
    status: "ACTIVE" as const,
    tipo: "seccion" as const,
    seccion: "Actividad 4 — Semana Técnica",
  },
];

export const INITIAL_ARTIFACT_EVENTOS_CORRECCION: DocumentArtifact = {
  ...INITIAL_ARTIFACT,
  codigoFormatoOficial: "UTA-SGC-A-2-1-P7-T1",
  carrera: "Ingeniería de Software",
  signatures: [
    {
      actorId: "usr-andrea-01",
      actor: "Ing. Andrea Pérez, Mg.",
      cargo: "Docente elaborador",
      role: "docente",
      fecha: "05/09/2026",
      hora: "23:41",
      ubicacion: "Firmas de Responsabilidad: Elaborado por",
    },
  ],
};

export const INITIAL_DOCUMENT_MASTER: DocumentMasterState = {
  id: "doc-plan-eventos-2026",
  teacherId: "usr-andrea-01",
  groupId: "grp-2",
  periodId: "per-1",
  codigo: "PT-FISEI-2026-004",
  codigoFormatoOficial: "UTA-SGC-A-2-1-P7-T1",
  nombre: "Plan de Trabajo: Comisión de Eventos Académicos",
  documentType: "PLAN_TRABAJO",
  grupo: "Comisión de Eventos Académicos",
  carrera: "Ingeniería de Software",
  periodo: "Julio – Diciembre 2026",
  formalVersion: "1.0",
  reviewRound: 1,
  documentState: "EN CORRECCIÓN",
  finalActionLabel: "VALIDADO_POR",
  finalValidatorId: "usr-patricia-03",
  finalValidatorName: "Ing. Patricia Salazar, Mg.",
  currentArtifact: INITIAL_ARTIFACT_EVENTOS_CORRECCION,
  artifactHistory: [],
  observations: OBSERVACIONES_INICIALES_EVENTOS,
  flowStages: [
    {
      id: "stage-1",
      actorId: "usr-andrea-01",
      stageName: "ETAPA 1 — Elaboración",
      actorName: "Ing. Andrea Pérez, Mg.",
      actorCargo: "Docente elaborador",
      actorRole: "docente",
      estado: "FIRMADO",
      actionLabel: "ELABORADO_POR",
    },
    {
      id: "stage-2",
      actorId: "usr-carlos-02",
      stageName: "ETAPA 2 — Revisión",
      subLevelName: "Nivel 1 — Revisión técnica",
      actorName: "Ing. Carlos López, Mg.",
      actorCargo: "Responsable de revisión técnica",
      actorRole: "revisor",
      estado: "DEVUELTO",
      actionLabel: "REVISADO_POR",
    },
    {
      id: "stage-3",
      actorId: "usr-patricia-03",
      stageName: "ETAPA 3 — Validación final",
      subLevelName: "Validación y Aprobación",
      actorName: "Ing. Patricia Salazar, Mg.",
      actorCargo: "Coordinadora de Unidad",
      actorRole: "validador",
      estado: "PENDIENTE",
      actionLabel: "VALIDADO_POR",
    },
  ],
  fechaUltimaActualizacion: "06/09/2026 11:30",
  mensajeDevolucion:
    "Ajustar el cronograma y recursos en la sección de ponencias magistrales, y especificar medios de verificación definitivos antes de reenviar.",
};

export const INITIAL_INFORME_ARTIFACT: DocumentArtifact = {
  id: "art-inf-titulacion-v1-r1",
  documentType: "INFORME",
  codigoFormatoOficial: "UTA-SGC-A-2-1-P7-T2",
  titulo: "SEGUIMIENTO DE ACTIVIDADES DE TITULACIÓN",
  formalVersion: "1.0",
  reviewRound: 1,
  get pageCount() { return this.pages?.length ?? 0; },
  generatedAt: "07/09/2026 10:00",
  generatedBy: "Ing. Carlos López, Mg.",
  grupo: "Unidad de Titulación",
  carrera: "Ingeniería de Software",
  periodo: "Julio – Diciembre 2026",
  unidadAcademica: "Facultad de Ingeniería en Sistemas, Electrónica e Industrial",
  elaborador: {
    id: "usr-carlos-02",
    nombre: "Ing. Carlos López, Mg.",
    cargo: "Docente elaborador",
    email: "carlos.lopez@uta.edu.ec",
  },
  informeData: {
    informeOrigen: "DERIVADO_PLAN",
    relatedPlanId: "doc-plan-titulacion-2026",
    relatedPlanTitulo: "Plan de Trabajo — Unidad de Titulación — Versión 1.0",
    antecedentes: "En cumplimiento a la planificación académica aprobada en el Plan de Trabajo de la Unidad de Titulación correspondiente al período académico Julio – Diciembre 2026, se presenta el informe de avance y cumplimiento de las actividades desarrolladas.",
    actividadesInforme: ACTIVIDADES_INFORME_TITULACION_INICIAL,
    conclusiones: "Se ejecutaron satisfactoriamente las jornadas de revisión y sustentación con un alto índice de cumplimiento del cronograma planificado.",
    oportunidadesMejora: "Fortalecer la articulación previa con los laboratorios y coordinar con mayor antelación las agendas de los tribunales de grado.",
    aplicaRegistroContactos: false,
    contactosDelegacion: [],
    introduccion: "En cumplimiento a la planificación académica aprobada en el Plan de Trabajo de la Unidad de Titulación correspondiente al período académico Julio – Diciembre 2026, se presenta el informe de avance y cumplimiento de las actividades desarrolladas.",
    desarrollo: "Se realizaron revisiones periódicas de los proyectos de grado, talleres de actualización metodológica y coordinación con los tribunales de sustentación para asegurar el cumplimiento del cronograma académico institucional.",
    resultados: "Se registró la aprobación de anteproyectos con cumplimiento de los estándares de calidad académica y vinculación con líneas de investigación de la FISEI.",
    observaciones: "Se recomienda mantener la articulación con los laboratorios de cómputo para futuras convocatorias.",
    documentoRelacionado: "Plan de Trabajo — Unidad de Titulación — Versión 1.0",
  },
  tieneAnexos: "no",
  anexos: [],
  signatures: [],
  historialCambios: [
    {
      version: "1.0",
      descripcion: "Elaboración inicial del Informe de seguimiento",
      fecha: "07/09/2026",
    },
  ],
};

export const INITIAL_INFORME_MASTER: DocumentMasterState = {
  id: "doc-inf-titulacion-2026",
  teacherId: "usr-carlos-02",
  groupId: "grp-1",
  periodId: "per-1",
  codigo: "INF-FISEI-2026-012",
  codigoFormatoOficial: "UTA-SGC-A-2-1-P7-T2",
  nombre: "SEGUIMIENTO DE ACTIVIDADES DE TITULACIÓN",
  documentType: "INFORME",
  grupo: "Unidad de Titulación",
  carrera: "Ingeniería de Software",
  periodo: "Julio – Diciembre 2026",
  formalVersion: "1.0",
  reviewRound: 1,
  documentState: "BORRADOR",
  finalActionLabel: "VALIDADO_POR",
  finalValidatorId: "usr-patricia-03",
  finalValidatorName: "Ing. Patricia Salazar, Mg.",
  currentArtifact: INITIAL_INFORME_ARTIFACT,
  artifactHistory: [],
  observations: [],
  flowStages: [
    {
      id: "stage-1",
      actorId: "usr-carlos-02",
      stageName: "ETAPA 1 — Elaboración",
      actorName: "Ing. Carlos López, Mg.",
      actorCargo: "Docente elaborador",
      actorRole: "docente",
      estado: "PENDIENTE",
      actionLabel: "ELABORADO_POR",
    },
    {
      id: "stage-2",
      actorId: "usr-carlos-02",
      stageName: "ETAPA 2 — Revisión",
      subLevelName: "Nivel 1 — Revisión técnica",
      actorName: "Ing. Carlos López, Mg.",
      actorCargo: "Responsable de revisión técnica",
      actorRole: "revisor",
      estado: "PENDIENTE",
      actionLabel: "REVISADO_POR",
    },
    {
      id: "stage-3",
      actorId: "usr-patricia-03",
      stageName: "ETAPA 3 — Validación final",
      subLevelName: "Validación y Aprobación",
      actorName: "Ing. Patricia Salazar, Mg.",
      actorCargo: "Coordinadora de Unidad",
      actorRole: "validador",
      estado: "PENDIENTE",
      actionLabel: "VALIDADO_POR",
    },
  ],
  fechaUltimaActualizacion: "07/09/2026 10:00",
  documentoRelacionadoId: "doc-plan-titulacion-2026",
  documentoRelacionadoTitulo: "Plan de Trabajo — Unidad de Titulación — Versión 1.0",
};

export const JUSTIFICACION_TITULACION = 'La Unidad de Titulación coordina, supervisa y evalúa los procesos de graduación de los estudiantes de la Facultad, asegurando el cumplimiento de la normativa institucional y los estándares de calidad académica en la revisión de proyectos de grado y sustentaciones.';
export const OBJETIVO_TITULACION = 'Planificar y ejecutar las actividades relacionadas con los procesos de titulación de los estudiantes durante el período Julio – Diciembre 2026, garantizando la correcta asignación de tribunales, revisión de proyectos y cumplimiento del cronograma académico.';
export const MATRIZ_TITULACION_DOC = [
  { id: 1, nombre: 'Seguimiento al avance de trabajos de titulación', desde: '02/09/2026', hasta: '18/09/2026', responsables: ['Ing. Andrea Pérez, Mg.'], recursos: ['Sistema Institucional'], medios: ['Reporte de seguimiento'] },
  { id: 2, nombre: 'Jornada informativa para estudiantes', desde: '03/09/2026', hasta: '06/09/2026', responsables: ['Ing. Andrea Pérez, Mg.'], recursos: ['Material digital'], medios: ['Registro de asistencia'] },
  { id: 3, nombre: 'Difusión de normativa interna de titulación', desde: '01/09/2026', hasta: '03/09/2026', responsables: ['Ing. Andrea Pérez, Mg.'], recursos: ['Medios digitales'], medios: ['Capturas de difusión'] },
  { id: 4, nombre: 'Revisión de planes de grado cohorte 2025', desde: '15/08/2026', hasta: '28/08/2026', responsables: ['Ing. Carlos López, Mg.'], recursos: ['Documentación física'], medios: ['Actas de revisión'] },
  { id: 5, nombre: 'Taller de inducción metodológica para tutores', desde: '05/08/2026', hasta: '15/08/2026', responsables: ['Ing. Andrea Pérez, Mg.'], recursos: ['Material didáctico'], medios: ['Registro de asistencia'] }
];

export const INITIAL_PLAN_TITULACION_MASTER: DocumentMasterState = {
  id: "doc-plan-titulacion-2026",
  teacherId: "usr-carlos-02",
  groupId: "grp-1",
  periodId: "per-1",
  codigo: "PT-FISEI-2026-001",
  codigoFormatoOficial: "UTA-SGC-A-2-1-P7-T1",
  nombre: "Plan de Trabajo: Unidad de Titulación",
  documentType: "PLAN_TRABAJO",
  grupo: "Unidad de Titulación",
  carrera: "Ingeniería de Software",
  periodo: "Julio – Diciembre 2026",
  formalVersion: "1.0",
  reviewRound: 1,
  documentState: "VALIDADO",
  operationalState: "EN EJECUCIÓN",
  finalActionLabel: "VALIDADO_POR",
  finalValidatorId: "usr-patricia-03",
  finalValidatorName: "Ing. Patricia Salazar, Mg.",
  currentArtifact: {
    ...INITIAL_ARTIFACT,
    id: "art-plan-titulacion-v1",
    codigoFormatoOficial: "UTA-SGC-A-2-1-P7-T1",
    titulo: "Plan de Trabajo: Unidad de Titulación",
    grupo: "Unidad de Titulación",
    carrera: "Ingeniería de Software",
    generatedBy: "Ing. Carlos López, Mg.",
    elaborador: {
      id: "usr-carlos-02",
      nombre: "Ing. Carlos López, Mg.",
      cargo: "Docente elaborador",
      email: "carlos.lopez@uta.edu.ec",
    },
    justificacion: JUSTIFICACION_TITULACION,
    objetivo: OBJETIVO_TITULACION,
    matriz: MATRIZ_TITULACION_DOC,
    anexos: [
      {
        id: 1,
        nombre: "Normativa interna de titulación",
        archivo: "normativa_titulacion_2026.pdf",
        tamano: "2.1 MB",
      },
    ],
    signatures: [
      {
        actorId: "usr-carlos-02",
        actor: "Ing. Carlos López, Mg.",
        cargo: "Docente elaborador",
        role: "docente",
        fecha: "05/09/2026",
        hora: "09:00",
        ubicacion: "Firmas de Responsabilidad: Elaborado por",
      },
      {
        actorId: "usr-carlos-02",
        actor: "Ing. Carlos López, Mg.",
        cargo: "Responsable de revisión técnica",
        role: "revisor",
        fecha: "06/09/2026",
        hora: "10:30",
        ubicacion: "Firmas de Responsabilidad: Revisado por",
      },
      {
        actorId: "usr-patricia-03",
        actor: "Ing. Patricia Salazar, Mg.",
        cargo: "Coordinadora de Unidad",
        role: "validador",
        fecha: "06/09/2026",
        hora: "15:00",
        ubicacion: "Firmas de Responsabilidad: Validado por",
      },
    ],
    historialCambios: [
      {
        version: "1.0",
        descripcion: "Elaboración del Plan de Trabajo",
        fecha: "06/09/2026",
      },
    ],
  },
  artifactHistory: [],
  observations: [],
  flowStages: [
    {
      id: "stage-1",
      actorId: "usr-carlos-02",
      stageName: "ETAPA 1 — Elaboración",
      actorName: "Ing. Carlos López, Mg.",
      actorCargo: "Docente elaborador",
      actorRole: "docente",
      estado: "FIRMADO",
      actionLabel: "ELABORADO_POR",
    },
    {
      id: "stage-2",
      actorId: "usr-carlos-02",
      stageName: "ETAPA 2 — Revisión",
      subLevelName: "Nivel 1 — Revisión técnica",
      actorName: "Ing. Carlos López, Mg.",
      actorCargo: "Responsable de revisión técnica",
      actorRole: "revisor",
      estado: "APROBADO",
      actionLabel: "REVISADO_POR",
    },
    {
      id: "stage-3",
      actorId: "usr-patricia-03",
      stageName: "ETAPA 3 — Validación final",
      subLevelName: "Validación y Aprobación",
      actorName: "Ing. Patricia Salazar, Mg.",
      actorCargo: "Coordinadora de Unidad",
      actorRole: "validador",
      estado: "FIRMADO",
      actionLabel: "VALIDADO_POR",
    },
  ],
  fechaUltimaActualizacion: "06/09/2026 15:00",
};

export const INITIAL_PLAN_ANDREA_VINCULACION_MASTER: DocumentMasterState = {
  ...INITIAL_PLAN_TITULACION_MASTER,
  id: "doc-plan-andrea-vinculacion-2026",
  teacherId: "usr-andrea-01",
  groupId: "grp-4",
  periodId: "per-1",
  codigo: "DEMO-PT-VINCULACION-ANDREA",
  nombre: "Plan de Trabajo: Comisión de Vinculación con la Sociedad",
  grupo: "Comisión de Vinculación con la Sociedad",
  currentArtifact: {
    ...INITIAL_PLAN_TITULACION_MASTER.currentArtifact,
    id: "art-plan-andrea-vinculacion-v1",
    titulo: "Plan de Trabajo: Comisión de Vinculación con la Sociedad",
    grupo: "Comisión de Vinculación con la Sociedad",
    generatedBy: "Ing. Andrea Pérez, Mg.",
    elaborador: { id: "usr-andrea-01", nombre: "Ing. Andrea Pérez, Mg.", cargo: "Docente elaborador", email: "andrea.perez@uta.edu.ec" },
    justificacion: "La Comisión de Vinculación con la Sociedad articula actividades académicas con actores externos para fortalecer la transferencia de conocimiento y el seguimiento de compromisos institucionales.",
    objetivo: "Coordinar y documentar las actividades de vinculación con la sociedad previstas para el período Julio – Diciembre 2026.",
    matriz: [
      { id: 1, nombre: "Seguimiento técnico de proyectos de vinculación activos", desde: "08/09/2026", hasta: "30/10/2026", responsables: ["Ing. Andrea Pérez, Mg."], responsableIds: ["usr-andrea-01"], responsableNames: ["Ing. Andrea Pérez, Mg."], recursos: ["Matriz de seguimiento", "Sala de reuniones"], medios: ["Informe", "Acta"] },
      { id: 2, nombre: "Socialización de resultados con las entidades participantes", desde: "03/11/2026", hasta: "11/12/2026", responsables: ["Ing. Andrea Pérez, Mg."], responsableIds: ["usr-andrea-01"], responsableNames: ["Ing. Andrea Pérez, Mg."], recursos: ["Equipos de cómputo"], medios: ["Informe", "Registro fotográfico"] },
    ],
    pages: undefined,
    pageCount: 0,
    signatureSlots: undefined,
    signatures: [
      { stageId: "andrea-vinc-stage-1", actorId: "usr-andrea-01", actor: "Ing. Andrea Pérez, Mg.", cargo: "Docente elaborador", role: "docente", fecha: "05/09/2026", hora: "09:00", ubicacion: "Firmas de Responsabilidad: Elaborado por", credentialMode: "demo", isDemo: true },
      { stageId: "andrea-vinc-stage-2", actorId: "usr-carlos-02", actor: "Ing. Carlos López, Mg.", cargo: "Responsable de revisión técnica", role: "revisor", fecha: "06/09/2026", hora: "10:30", ubicacion: "Firmas de Responsabilidad: Revisado por", credentialMode: "demo", isDemo: true },
      { stageId: "andrea-vinc-stage-3", actorId: "usr-patricia-03", actor: "Ing. Patricia Salazar, Mg.", cargo: "Validadora institucional", role: "validador", fecha: "06/09/2026", hora: "15:00", ubicacion: "Firmas de Responsabilidad: Validado por", credentialMode: "demo", isDemo: true },
    ],
  },
  flowStages: [
    { id: "andrea-vinc-stage-1", actorId: "usr-andrea-01", stageName: "ETAPA 1 — Elaboración", actorName: "Ing. Andrea Pérez, Mg.", actorCargo: "Docente elaborador", actorRole: "docente", estado: "FIRMADO", actionLabel: "ELABORADO_POR" },
    { id: "andrea-vinc-stage-2", actorId: "usr-carlos-02", stageName: "ETAPA 2 — Revisión", actorName: "Ing. Carlos López, Mg.", actorCargo: "Responsable de revisión técnica", actorRole: "revisor", estado: "APROBADO", actionLabel: "REVISADO_POR" },
    { id: "andrea-vinc-stage-3", actorId: "usr-patricia-03", stageName: "ETAPA 3 — Validación final", actorName: "Ing. Patricia Salazar, Mg.", actorCargo: "Validadora institucional", actorRole: "validador", estado: "FIRMADO", actionLabel: "VALIDADO_POR" },
  ],
};

export const INITIAL_PLAN_CLUB_DRAFT_MASTER: DocumentMasterState = {
  ...INITIAL_DOCUMENT_MASTER,
  id: "doc-plan-club-2026-1",
  teacherId: "usr-andrea-01",
  groupId: "grp-3",
  periodId: "per-2",
  codigo: "DEMO-PT-CLUB-BORRADOR",
  nombre: "Plan de Trabajo: Club Académico de Software",
  grupo: "Club Académico de Software",
  periodo: "Enero – Junio 2026",
  documentState: "BORRADOR",
  currentArtifact: {
    ...INITIAL_ARTIFACT,
    id: "art-plan-club-borrador",
    titulo: "Plan de Trabajo: Club Académico de Software",
    grupo: "Club Académico de Software",
    periodo: "Enero – Junio 2026",
    matriz: [],
    tieneAnexos: "no",
    anexos: [],
    signatures: [],
  },
  observations: [],
  flowStages: [
    { ...FLOW_STAGES_INICIAL[0], estado: "PENDIENTE" },
    { ...FLOW_STAGES_INICIAL[1], id: "club-pending", actorId: undefined, actorName: "Responsable pendiente de configuración", stageName: "Etapa pendiente de configuración", estado: "PENDIENTE" },
  ],
  mensajeDevolucion: undefined,
};

export const INITIAL_PLAN_VINCULACION_REVISION_MASTER: DocumentMasterState = {
  ...INITIAL_DOCUMENT_MASTER,
  id: "doc-plan-vinculacion-2026",
  teacherId: "usr-carlos-02",
  groupId: "grp-4",
  periodId: "per-1",
  codigo: "DEMO-PT-VINCULACION-REVISION",
  nombre: "Plan de Trabajo: Comisión de Vinculación con la Sociedad",
  grupo: "Comisión de Vinculación con la Sociedad",
  periodo: "Julio – Diciembre 2026",
  documentState: "EN REVISIÓN",
  currentArtifact: {
    ...INITIAL_ARTIFACT,
    id: "art-plan-vinculacion-revision",
    titulo: "Plan de Trabajo: Comisión de Vinculación con la Sociedad",
    grupo: "Comisión de Vinculación con la Sociedad",
    elaborador: { id: "usr-carlos-02", nombre: "Ing. Carlos López, Mg.", cargo: "Docente elaborador", email: "carlos.lopez@uta.edu.ec" },
    generatedBy: "Ing. Carlos López, Mg.",
    signatures: [{ actorId: "usr-carlos-02", stageId: "vinc-stage-1", actor: "Ing. Carlos López, Mg.", cargo: "Docente elaborador", role: "docente", fecha: "05/09/2026", hora: "09:00", ubicacion: "Firmas de Responsabilidad: Elaborado por", credentialMode: "demo", isDemo: true }],
  },
  observations: [],
  flowStages: [
    { ...FLOW_STAGES_INICIAL[0], id: "vinc-stage-1", actorId: "usr-carlos-02", actorName: "Ing. Carlos López, Mg.", estado: "FIRMADO" },
    { ...FLOW_STAGES_INICIAL[1], id: "vinc-stage-2", actorId: "usr-andrea-01", actorName: "Ing. Andrea Pérez, Mg.", estado: "EN_CURSO" },
    { ...FLOW_STAGES_INICIAL[2], id: "vinc-stage-3", estado: "PENDIENTE" },
  ],
  mensajeDevolucion: undefined,
};

export const INITIAL_DOCUMENTS_LIST: DocumentMasterState[] = [
  INITIAL_PLAN_TITULACION_MASTER,
  INITIAL_PLAN_ANDREA_VINCULACION_MASTER,
  INITIAL_DOCUMENT_MASTER,
  INITIAL_INFORME_MASTER,
  INITIAL_PLAN_CLUB_DRAFT_MASTER,
  INITIAL_PLAN_VINCULACION_REVISION_MASTER,
];



