// Módulo 8 — Datos Mock de Notificaciones, Auditoría y Trazabilidad Institucional
import { NotificacionItem, AuditoriaEvento, TrazabilidadObjeto } from "./types";

// ─── NOTIFICACIONES DEMO ──────────────────────────────────────────────────────

export const NOTIFICACIONES_DOCENTE: NotificacionItem[] = [
  {
    id: "notif-doc-1",
    destinatarioRol: "Docente",
    destinatarioUsuarioId: "docente-andrea",
    titulo: "Plan devuelto con observaciones",
    mensaje: "El Plan de Trabajo de Comisión de Eventos Académicos requiere correcciones registradas por el revisor.",
    fechaHora: "07/09/2026 — 09:35",
    tiempoRelativo: "Hace 55 min",
    tipo: "PLAN_DEVUELTO",
    leida: false,
    objetoRelacionado: {
      tipo: "Plan de Trabajo",
      nombre: "Comisión de Eventos Académicos",
      grupo: "Comisión de Eventos Académicos",
      autor: "Ing. Carlos López, Mg.",
      accionLabel: "VER OBSERVACIONES",
      accionDestino: "planes",
      modalDirecto: "obsPlan",
    },
  },
  {
    id: "notif-doc-2",
    destinatarioRol: "Docente",
    destinatarioUsuarioId: "docente-andrea",
    titulo: "Evidencia observada",
    mensaje: "La evidencia 'Acta' cargada en la actividad 'Seguimiento al avance de trabajos de titulación' requiere revisión.",
    fechaHora: "07/09/2026 — 10:28",
    tiempoRelativo: "Hace 15 min",
    tipo: "EVIDENCIA_OBSERVADA",
    leida: false,
    objetoRelacionado: {
      tipo: "Evidencia",
      nombre: "Acta — Unidad de Titulación",
      grupo: "Unidad de Titulación",
      autor: "Ing. Carlos López, Mg.",
      accionLabel: "VER OBSERVACIÓN",
      accionDestino: "actividades",
      actividadId: "act-1",
      medioId: "medio-1",
      modalDirecto: "observacion",
    },
  },
  {
    id: "notif-doc-3",
    destinatarioRol: "Docente",
    destinatarioUsuarioId: "docente-andrea",
    titulo: "Evidencia validada",
    mensaje: "La evidencia 'Informe técnico' ha sido validada satisfactoriamente por el revisor asignado.",
    fechaHora: "07/09/2026 — 08:30",
    tiempoRelativo: "Hace 2 h",
    tipo: "EVIDENCIA_VALIDADA",
    leida: true,
    objetoRelacionado: {
      tipo: "Evidencia",
      nombre: "Informe técnico — v1.0",
      grupo: "Unidad de Titulación",
      autor: "Ing. Carlos López, Mg.",
      accionLabel: "VER EVIDENCIA",
      accionDestino: "actividades",
      actividadId: "act-1",
      medioId: "medio-2",
      modalDirecto: "visor",
    },
  },
  {
    id: "notif-doc-4",
    destinatarioRol: "Docente",
    destinatarioUsuarioId: "docente-andrea",
    titulo: "Actividad próxima a vencer",
    mensaje: "La actividad 'Presentación de informes mensuales de comisiones' vence el 12/09/2026 (faltan 5 días).",
    fechaHora: "07/09/2026 — 07:45",
    tiempoRelativo: "Hace 3 h",
    tipo: "ACTIVIDAD_PROXIMA",
    leida: true,
    objetoRelacionado: {
      tipo: "Actividad",
      nombre: "Presentación de informes mensuales de comisiones",
      grupo: "Unidad de Titulación",
      accionLabel: "VER ACTIVIDAD",
      accionDestino: "actividades",
      actividadId: "act-13",
    },
  },
  {
    id: "notif-doc-5",
    destinatarioRol: "Docente",
    destinatarioUsuarioId: "docente-andrea",
    titulo: "Asignación a grupo institucional",
    mensaje: "Ha sido asignada como Miembro al grupo 'Unidad de Titulación' para el período Julio – Diciembre 2026.",
    fechaHora: "05/09/2026 — 10:15",
    tiempoRelativo: "Hace 2 días",
    tipo: "ADMIN_CATALOGO_ACTUALIZADO",
    leida: true,
    objetoRelacionado: {
      tipo: "Configuración",
      nombre: "Unidad de Titulación",
      grupo: "Unidad de Titulación",
      accionLabel: "VER PLANES",
      accionDestino: "planes",
    },
  },
];

export const NOTIFICACIONES_REVISOR: NotificacionItem[] = [
  {
    id: "notif-rev-1",
    destinatarioRol: "Revisor",
    destinatarioUsuarioId: "revisor-carlos",
    titulo: "Nuevo Plan de Trabajo pendiente de revisión",
    mensaje: "El Plan de Trabajo de la Unidad de Titulación remitido por Ing. Andrea Pérez, Mg. se encuentra en revisión.",
    fechaHora: "07/09/2026 — 09:10",
    tiempoRelativo: "Hace 1 h",
    tipo: "PLAN_PENDIENTE_REVISION",
    leida: false,
    objetoRelacionado: {
      tipo: "Plan de Trabajo",
      nombre: "Unidad de Titulación — v1.0",
      grupo: "Unidad de Titulación",
      autor: "Ing. Andrea Pérez, Mg.",
      accionLabel: "REVISAR PLAN",
      accionDestino: "bandeja",
      modalDirecto: "revisionPlan",
    },
  },
  {
    id: "notif-rev-2",
    destinatarioRol: "Revisor",
    destinatarioUsuarioId: "revisor-carlos",
    titulo: "Nueva evidencia pendiente de validación",
    mensaje: "Se cargó la evidencia 'Oficio de designación' en la actividad 'Seguimiento al avance de titulación'.",
    fechaHora: "07/09/2026 — 10:15",
    tiempoRelativo: "Hace 25 min",
    tipo: "EVIDENCIA_CARGADA",
    leida: false,
    objetoRelacionado: {
      tipo: "Evidencia",
      nombre: "Oficio — v1.0",
      grupo: "Unidad de Titulación",
      autor: "Ing. Andrea Pérez, Mg.",
      accionLabel: "REVISAR EVIDENCIA",
      accionDestino: "evidenciasValidar",
      actividadId: "act-1",
      medioId: "medio-1",
    },
  },
  {
    id: "notif-rev-3",
    destinatarioRol: "Revisor",
    destinatarioUsuarioId: "revisor-carlos",
    titulo: "Plan corregido reenviado",
    mensaje: "Se recibió la corrección del Plan de Trabajo de la Comisión de Eventos Académicos para nueva revisión técnica.",
    fechaHora: "06/09/2026 — 16:20",
    tiempoRelativo: "Ayer",
    tipo: "PLAN_CORREGIDO",
    leida: true,
    objetoRelacionado: {
      tipo: "Plan de Trabajo",
      nombre: "Plan de Trabajo — Comisión de Eventos Académicos",
      grupo: "Comisión de Eventos Académicos",
      autor: "Ing. Andrea Pérez, Mg.",
      accionLabel: "REVISAR PLAN",
      accionDestino: "bandeja",
      modalDirecto: "revisionPlan",
    },
  },
  {
    id: "notif-rev-4",
    destinatarioRol: "Revisor",
    destinatarioUsuarioId: "revisor-carlos",
    titulo: "Evidencia observada reemplazada",
    mensaje: "Ing. Andrea Pérez, Mg. cargó la versión corregida 'Acta — v2.0' pendiente de nueva validación.",
    fechaHora: "07/09/2026 — 10:30",
    tiempoRelativo: "Hace 10 min",
    tipo: "EVIDENCIA_REEMPLAZADA",
    leida: true,
    objetoRelacionado: {
      tipo: "Evidencia",
      nombre: "Acta — v2.0",
      grupo: "Unidad de Titulación",
      autor: "Ing. Andrea Pérez, Mg.",
      accionLabel: "REVISAR EVIDENCIA",
      accionDestino: "evidenciasValidar",
      actividadId: "act-1",
      medioId: "medio-1",
    },
  },
];

export const NOTIFICACIONES_ADMIN: NotificacionItem[] = [
  {
    id: "notif-adm-1",
    destinatarioRol: "Administrador",
    destinatarioUsuarioId: "admin-laura",
    titulo: "Grupo sin flujo configurado",
    mensaje: "El grupo 'Club Académico de Software' no cuenta con un flujo de aprobación formal asignado.",
    fechaHora: "07/09/2026 — 08:00",
    tiempoRelativo: "Hace 3 h",
    tipo: "ADMIN_GRUPO_SIN_FLUJO",
    leida: false,
    objetoRelacionado: {
      tipo: "Configuración",
      nombre: "Club Académico de Software",
      grupo: "Club Académico de Software",
      accionLabel: "VER CONFIGURACIÓN",
      accionDestino: "adminFlujos",
    },
  },
  {
    id: "notif-adm-2",
    destinatarioRol: "Administrador",
    destinatarioUsuarioId: "admin-laura",
    titulo: "Nuevo período académico preparado",
    mensaje: "Se ha configurado la ventana operativa para el período académico 'Julio – Diciembre 2026'.",
    fechaHora: "05/09/2026 — 11:00",
    tiempoRelativo: "Hace 2 días",
    tipo: "ADMIN_PERIODO_PREPARADO",
    leida: true,
    objetoRelacionado: {
      tipo: "Configuración",
      nombre: "Período Julio – Diciembre 2026",
      accionLabel: "VER PERÍODOS",
      accionDestino: "adminPeriodos",
    },
  },
  {
    id: "notif-adm-3",
    destinatarioRol: "Administrador",
    destinatarioUsuarioId: "admin-laura",
    titulo: "Configuración de catálogo institucional actualizada",
    mensaje: "Se incorporó el medio de verificación institucional 'Registro digital de asistencia'.",
    fechaHora: "06/09/2026 — 17:15",
    tiempoRelativo: "Ayer",
    tipo: "ADMIN_CATALOGO_ACTUALIZADO",
    leida: true,
    objetoRelacionado: {
      tipo: "Configuración",
      nombre: "Catálogo de Medios de Verificación",
      accionLabel: "VER CATÁLOGOS",
      accionDestino: "adminCatalogos",
    },
  },
];

// ─── EVENTOS DE AUDITORÍA DEMO ───────────────────────────────────────────────
// Mantener EXACTAMENTE métricas de Pantalla 02 para 07/09/2026:
// Eventos hoy: 18 | Acciones de planes: 7 | Acciones de evidencias: 8 | Cambios administrativos: 3

export const AUDITORIA_EVENTOS_DEMO: AuditoriaEvento[] = [
  // ── HOY: 07/09/2026 (18 eventos en total) ─────────────────────────────────
  // 1. Accion Admin (1/3 hoy)
  {
    id: "aud-01",
    fechaHora: "07/09/2026 — 11:00",
    fecha: "07/09/2026",
    hora: "11:00",
    usuario: "Ing. Laura Medina, Mg.",
    rol: "Administrador",
    modulo: "Administración",
    accion: "MODIFICÓ CONFIGURACIÓN",
    tipoEvento: "Cambio de configuración",
    objeto: "Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Actualización de flujos de aprobación y asignación de revisores institucionales para la Unidad de Titulación.",
    estadoAnterior: "CONFIGURACIÓN PREVIA",
    estadoPosterior: "CONFIGURACIÓN ACTUALIZADA",
    objetoId: "grupo-ut",
    tipoObjeto: "Configuracion",
  },
  // 2. Accion Evidencia (1/8 hoy)
  {
    id: "aud-02",
    fechaHora: "07/09/2026 — 10:35",
    fecha: "07/09/2026",
    hora: "10:35",
    usuario: "Ing. Carlos López, Mg.",
    rol: "Revisor",
    modulo: "Evidencias",
    accion: "VALIDÓ EVIDENCIA",
    tipoEvento: "Validación",
    objeto: "Informe — v1.0",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Ing. Carlos López, Mg. validó satisfactoriamente el medio de verificación 'Informe — v1.0' conforme a los criterios de cumplimiento.",
    estadoAnterior: "PENDIENTE DE VALIDACIÓN",
    estadoPosterior: "VALIDADA",
    objetoId: "evidencia-acta-ut",
    tipoObjeto: "Evidencia",
  },
  // 3. Accion Evidencia (2/8 hoy)
  {
    id: "aud-03",
    fechaHora: "07/09/2026 — 10:30",
    fecha: "07/09/2026",
    hora: "10:30",
    usuario: "Ing. Andrea Pérez, Mg.",
    rol: "Docente",
    modulo: "Evidencias",
    accion: "REEMPLAZÓ EVIDENCIA",
    tipoEvento: "Reemplazo",
    objeto: "Acta — v2.0",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Ing. Andrea Pérez, Mg. cargó la versión corregida del medio 'Acta — v2.0' solventando las observaciones de firmas.",
    estadoAnterior: "OBSERVADA",
    estadoPosterior: "PENDIENTE DE VALIDACIÓN",
    objetoId: "evidencia-acta-ut",
    tipoObjeto: "Evidencia",
  },
  // 4. Accion Evidencia (3/8 hoy)
  {
    id: "aud-04",
    fechaHora: "07/09/2026 — 10:28",
    fecha: "07/09/2026",
    hora: "10:28",
    usuario: "Ing. Carlos López, Mg.",
    rol: "Revisor",
    modulo: "Evidencias",
    accion: "OBSERVÓ EVIDENCIA",
    tipoEvento: "Observación",
    objeto: "Acta — v1.0",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Ing. Carlos López, Mg. registró una observación sobre la evidencia 'Acta', versión 1.0: Falta firma de constancia de asistencia del tutor.",
    estadoAnterior: "PENDIENTE DE VALIDACIÓN",
    estadoPosterior: "OBSERVADA",
    objetoId: "evidencia-acta-ut",
    tipoObjeto: "Evidencia",
  },
  // 5. Accion Evidencia (4/8 hoy)
  {
    id: "aud-05",
    fechaHora: "07/09/2026 — 10:15",
    fecha: "07/09/2026",
    hora: "10:15",
    usuario: "Ing. Andrea Pérez, Mg.",
    rol: "Docente",
    modulo: "Evidencias",
    accion: "CARGÓ EVIDENCIA",
    tipoEvento: "Carga",
    objeto: "Oficio — v1.0",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Carga de documento digital de asignación y designación oficial de tutorías.",
    estadoAnterior: "PENDIENTE",
    estadoPosterior: "PENDIENTE DE VALIDACIÓN",
    objetoId: "evidencia-oficio-ut",
    tipoObjeto: "Evidencia",
  },
  // 6. Accion Admin (2/3 hoy) — CASO L: OPCIONAL -> OBLIGATORIA
  {
    id: "aud-06",
    fechaHora: "07/09/2026 — 09:50",
    fecha: "07/09/2026",
    hora: "09:50",
    usuario: "Ing. Laura Medina, Mg.",
    rol: "Administrador",
    modulo: "Administración",
    accion: "MODIFICÓ OBLIGATORIEDAD DE ACTIVIDAD",
    tipoEvento: "Modificación",
    objeto: "Consolidación del banco de reactivos",
    grupo: "Comisión Académica",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Ing. Laura Medina, Mg. modificó la condición reglamentaria de la actividad institucional 'Consolidación del banco de reactivos'.",
    estadoAnterior: "OPCIONAL",
    estadoPosterior: "OBLIGATORIA",
    objetoId: "act-banco-reactivos",
    tipoObjeto: "Actividad",
  },
  // 7. Accion Plan (1/7 hoy)
  {
    id: "aud-07",
    fechaHora: "07/09/2026 — 09:35",
    fecha: "07/09/2026",
    hora: "09:35",
    usuario: "Ing. Carlos López, Mg.",
    rol: "Revisor",
    modulo: "Planes de Trabajo",
    accion: "DEVOLVIÓ PLAN DE TRABAJO",
    tipoEvento: "Devolución",
    objeto: "Plan de Trabajo — v1.0",
    grupo: "Comisión de Eventos Académicos",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Ing. Carlos López, Mg. devolvió el Plan de Trabajo v1.0 indicando observaciones en el cronograma de conferencias y recursos.",
    estadoAnterior: "EN REVISIÓN",
    estadoPosterior: "DEVUELTO",
    objetoId: "plan-comision-eventos",
    tipoObjeto: "Plan",
  },
  // 8. Accion Plan (2/7 hoy)
  {
    id: "aud-08",
    fechaHora: "07/09/2026 — 09:30",
    fecha: "07/09/2026",
    hora: "09:30",
    usuario: "Ing. Carlos López, Mg.",
    rol: "Revisor",
    modulo: "Planes de Trabajo",
    accion: "REGISTRÓ OBSERVACIÓN EN PLAN",
    tipoEvento: "Observación",
    objeto: "Plan de Trabajo — v1.0",
    grupo: "Comisión de Eventos Académicos",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Registro de observación formal: Especificar medios de difusión y fechas definitivas de ponencias magistrales.",
    objetoId: "plan-comision-eventos",
    tipoObjeto: "Plan",
  },
  // 9. Accion Admin (3/3 hoy)
  {
    id: "aud-09",
    fechaHora: "07/09/2026 — 09:15",
    fecha: "07/09/2026",
    hora: "09:15",
    usuario: "Ing. Laura Medina, Mg.",
    rol: "Administrador",
    modulo: "Usuarios",
    accion: "ASIGNÓ USUARIO A GRUPO",
    tipoEvento: "Asignación",
    objeto: "Ing. Andrea Pérez, Mg.",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Asignación de la docente Ing. Andrea Pérez, Mg. con rol Miembro dentro del grupo institucional Unidad de Titulación.",
    objetoId: "user-andrea",
    tipoObjeto: "Usuario",
  },
  // 10. Accion Plan (3/7 hoy)
  {
    id: "aud-10",
    fechaHora: "07/09/2026 — 09:10",
    fecha: "07/09/2026",
    hora: "09:10",
    usuario: "Ing. Andrea Pérez, Mg.",
    rol: "Docente",
    modulo: "Planes de Trabajo",
    accion: "ENVIÓ PLAN A REVISIÓN",
    tipoEvento: "Envío",
    objeto: "Plan de Trabajo — v1.0",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Ing. Andrea Pérez, Mg. remitió el Plan de Trabajo v1.0 debidamente completado para la etapa de revisión técnica.",
    estadoAnterior: "BORRADOR",
    estadoPosterior: "EN REVISIÓN",
    objetoId: "plan-titulacion-andrea",
    tipoObjeto: "Plan",
  },
  // 11. Accion Plan (4/7 hoy)
  {
    id: "aud-11",
    fechaHora: "07/09/2026 — 08:50",
    fecha: "07/09/2026",
    hora: "08:50",
    usuario: "Ing. Andrea Pérez, Mg.",
    rol: "Docente",
    modulo: "Planes de Trabajo",
    accion: "INICIÓ CORRECCIÓN DE PLAN",
    tipoEvento: "Modificación",
    objeto: "Plan de Trabajo — v1.0",
    grupo: "Comisión de Eventos Académicos",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Ing. Andrea Pérez, Mg. abrió el Plan devuelto para solventar observaciones técnicas (se mantiene v1.0).",
    estadoAnterior: "DEVUELTO",
    estadoPosterior: "EN CORRECCIÓN",
    objetoId: "plan-comision-eventos",
    tipoObjeto: "Plan",
  },
  // 12. Accion Evidencia (5/8 hoy)
  {
    id: "aud-12",
    fechaHora: "07/09/2026 — 08:35",
    fecha: "07/09/2026",
    hora: "08:35",
    usuario: "Ing. Andrea Pérez, Mg.",
    rol: "Docente",
    modulo: "Evidencias",
    accion: "CARGÓ EVIDENCIA",
    tipoEvento: "Carga",
    objeto: "Informe técnico — v1.0",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Carga del informe mensual de avance de estudiantes en modalidad de titulación.",
    estadoAnterior: "PENDIENTE",
    estadoPosterior: "PENDIENTE DE VALIDACIÓN",
    objetoId: "evidencia-informe-ut",
    tipoObjeto: "Evidencia",
  },
  // 13. Accion Plan (5/7 hoy)
  {
    id: "aud-13",
    fechaHora: "07/09/2026 — 08:20",
    fecha: "07/09/2026",
    hora: "08:20",
    usuario: "Ing. Carlos López, Mg.",
    rol: "Revisor",
    modulo: "Planes de Trabajo",
    accion: "REVISÓ ETAPA DE PLAN",
    tipoEvento: "Revisión",
    objeto: "Plan de Trabajo — v1.0",
    grupo: "Comisión de Eventos Académicos",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Aprobación de la etapa 1 de revisión técnica y avance a validación de coordinación para la Comisión de Eventos Académicos.",
    estadoAnterior: "EN REVISIÓN",
    estadoPosterior: "ETAPA COMPLETADA",
    objetoId: "plan-comision-eventos",
    tipoObjeto: "Plan",
  },
  // 14. Accion Evidencia (6/8 hoy)
  {
    id: "aud-14",
    fechaHora: "07/09/2026 — 08:15",
    fecha: "07/09/2026",
    hora: "08:15",
    usuario: "Ing. Carlos López, Mg.",
    rol: "Revisor",
    modulo: "Evidencias",
    accion: "VALIDÓ EVIDENCIA",
    tipoEvento: "Validación",
    objeto: "Registro de firmas — v1.0",
    grupo: "Comisión de Prácticas Preprofesionales",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Validación de listado oficial de convenios de prácticas vigentes.",
    estadoAnterior: "PENDIENTE DE VALIDACIÓN",
    estadoPosterior: "VALIDADA",
    objetoId: "evidencia-convenios",
    tipoObjeto: "Evidencia",
  },
  // 15. Accion Plan (6/7 hoy)
  {
    id: "aud-15",
    fechaHora: "07/09/2026 — 08:05",
    fecha: "07/09/2026",
    hora: "08:05",
    usuario: "Ing. Carlos López, Mg.",
    rol: "Revisor",
    modulo: "Planes de Trabajo",
    accion: "APROBÓ PLAN FINALMENTE",
    tipoEvento: "Aprobación",
    objeto: "Plan de Trabajo — v1.0",
    grupo: "Comisión de Investigación y Vinculación",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Plan de Trabajo aprobado formalmente y habilitado de inmediato para ejecución institucional.",
    estadoAnterior: "EN REVISIÓN",
    estadoPosterior: "EN EJECUCIÓN",
    objetoId: "plan-investigacion",
    tipoObjeto: "Plan",
  },
  // 16. Accion Evidencia (7/8 hoy)
  {
    id: "aud-16",
    fechaHora: "07/09/2026 — 07:50",
    fecha: "07/09/2026",
    hora: "07:50",
    usuario: "Ing. Andrea Pérez, Mg.",
    rol: "Docente",
    modulo: "Evidencias",
    accion: "CARGÓ EVIDENCIA",
    tipoEvento: "Carga",
    objeto: "Rúbrica de evaluación — v1.0",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Carga de matriz institucional de calificación de proyectos de titulación.",
    estadoAnterior: "PENDIENTE",
    estadoPosterior: "PENDIENTE DE VALIDACIÓN",
    objetoId: "evidencia-rubrica",
    tipoObjeto: "Evidencia",
  },
  // 17. Accion Plan (7/7 hoy)
  {
    id: "aud-17",
    fechaHora: "07/09/2026 — 07:30",
    fecha: "07/09/2026",
    hora: "07:30",
    usuario: "Ing. Andrea Pérez, Mg.",
    rol: "Docente",
    modulo: "Planes de Trabajo",
    accion: "GUARDÓ BORRADOR DE PLAN",
    tipoEvento: "Modificación",
    objeto: "Plan de Trabajo — v1.0",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Guardado de modificaciones en la sección de cronograma y horas asignadas.",
    objetoId: "plan-titulacion-andrea",
    tipoObjeto: "Plan",
  },
  // 18. Accion Evidencia (8/8 hoy)
  {
    id: "aud-18",
    fechaHora: "07/09/2026 — 07:15",
    fecha: "07/09/2026",
    hora: "07:15",
    usuario: "Ing. Carlos López, Mg.",
    rol: "Revisor",
    modulo: "Evidencias",
    accion: "OBSERVÓ EVIDENCIA",
    tipoEvento: "Observación",
    objeto: "Formato de seguimiento — v1.0",
    grupo: "Comisión de Vinculación",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Observación de formato: La fecha de emisión no coincide con el cronograma acordado.",
    estadoAnterior: "PENDIENTE DE VALIDACIÓN",
    estadoPosterior: "OBSERVADA",
    objetoId: "evidencia-seguimiento-vinc",
    tipoObjeto: "Evidencia",
  },

  // ── HISTÓRICOS ANTERIORES: 06/09/2026 y 05/09/2026 (Para Trazabilidad Completa) ──
  // 19. Accion Evidencia
  {
    id: "aud-19",
    fechaHora: "06/09/2026 — 15:20",
    fecha: "06/09/2026",
    hora: "15:20",
    usuario: "Ing. Andrea Pérez, Mg.",
    rol: "Docente",
    modulo: "Evidencias",
    accion: "CARGÓ EVIDENCIA",
    tipoEvento: "Carga",
    objeto: "Acta — v1.0",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Ing. Andrea Pérez, Mg. cargó la versión inicial 'Acta — v1.0' en formato PDF.",
    estadoAnterior: "PENDIENTE",
    estadoPosterior: "PENDIENTE DE VALIDACIÓN",
    objetoId: "evidencia-acta-ut",
    tipoObjeto: "Evidencia",
  },
  // 20. Accion Plan
  {
    id: "aud-20",
    fechaHora: "06/09/2026 — 10:30",
    fecha: "06/09/2026",
    hora: "10:30",
    usuario: "Ing. Carlos López, Mg.",
    rol: "Revisor",
    modulo: "Planes de Trabajo",
    accion: "DEVOLVIÓ PLAN",
    tipoEvento: "Devolución",
    objeto: "Plan de Trabajo — v1.0",
    grupo: "Comisión de Eventos Académicos",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Carlos López devolvió el plan por observaciones pendientes en presupuesto y fechas.",
    estadoAnterior: "EN REVISIÓN",
    estadoPosterior: "DEVUELTO",
    objetoId: "plan-comision-eventos",
    tipoObjeto: "Plan",
  },
  // 21. Accion Plan
  {
    id: "aud-21",
    fechaHora: "06/09/2026 — 10:25",
    fecha: "06/09/2026",
    hora: "10:25",
    usuario: "Ing. Carlos López, Mg.",
    rol: "Revisor",
    modulo: "Planes de Trabajo",
    accion: "OBSERVACIÓN REGISTRADA",
    tipoEvento: "Observación",
    objeto: "Plan de Trabajo — v1.0",
    grupo: "Comisión de Eventos Académicos",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Observación registrada: Corregir el número de horas asignadas al módulo de conferencias.",
    objetoId: "plan-comision-eventos",
    tipoObjeto: "Plan",
  },
  // 22. Accion Plan
  {
    id: "aud-22",
    fechaHora: "06/09/2026 — 09:15",
    fecha: "06/09/2026",
    hora: "09:15",
    usuario: "Ing. Andrea Pérez, Mg.",
    rol: "Docente",
    modulo: "Planes de Trabajo",
    accion: "ENVIÓ PLAN A REVISIÓN",
    tipoEvento: "Envío",
    objeto: "Plan de Trabajo — v1.0",
    grupo: "Comisión de Eventos Académicos",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Ing. Andrea Pérez, Mg. remitió el Plan de Trabajo firmado para revisión técnica.",
    estadoAnterior: "BORRADOR",
    estadoPosterior: "EN REVISIÓN",
    objetoId: "plan-comision-eventos",
    tipoObjeto: "Plan",
  },
  // 23. Accion Plan / Firma (CASO K: Datos sensibles no expuestos)
  {
    id: "aud-23",
    fechaHora: "05/09/2026 — 23:41",
    fecha: "05/09/2026",
    hora: "23:41",
    usuario: "Ing. Andrea Pérez, Mg.",
    rol: "Docente",
    modulo: "Planes de Trabajo",
    accion: "FIRMÓ PLAN DE TRABAJO",
    tipoEvento: "Firma",
    objeto: "Plan de Trabajo — v1.0",
    grupo: "Comisión de Eventos Académicos",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Documento firmado electrónicamente mediante certificado digital validado por el sistema institucional.",
    objetoId: "plan-comision-eventos",
    tipoObjeto: "Plan",
    firmaElectronicaInfo: {
      firmante: "Ing. Andrea Pérez, Mg.",
      documento: "Plan de Trabajo — Comisión de Eventos Académicos v1.0",
      fechaHora: "05/09/2026 — 23:41",
    },
  },
  // 24. Accion Admin
  {
    id: "aud-24",
    fechaHora: "05/09/2026 — 14:10",
    fecha: "05/09/2026",
    hora: "14:10",
    usuario: "Ing. Laura Medina, Mg.",
    rol: "Administrador",
    modulo: "Períodos",
    accion: "CONFIGURACIÓN DEL PERÍODO ACTUALIZADA",
    tipoEvento: "Modificación",
    objeto: "Julio – Diciembre 2026",
    grupo: "Facultad FISEI",
    periodo: "Julio – Diciembre 2026",
    descripcion: "Se actualizaron las ventanas de elaboración y revisión configuradas para el período académico Julio – Diciembre 2026.",
    estadoAnterior: "CONFIGURACIÓN ANTERIOR",
    estadoPosterior: "CONFIGURACIÓN ACTUALIZADA",
    objetoId: "periodo-2026",
    tipoObjeto: "Configuracion",
  },
];

// ─── TRAZABILIDAD POR OBJETO (TIMELINES INSTITUCIONALES) ──────────────────────

export const TRAZABILIDAD_PLAN_EVENTOS: TrazabilidadObjeto = {
  id: "plan-comision-eventos",
  tipo: "Plan",
  titulo: "Plan de Trabajo — Comisión de Eventos Académicos",
  subtitulo: "Versión formal 1.0 • Período Julio – Diciembre 2026",
  hitos: [
    {
      id: "th-p-1",
      fechaHora: "05/09/2026 — 23:41",
      usuario: "Ing. Andrea Pérez, Mg.",
      rol: "Docente elaboradora",
      hito: "PLAN FIRMADO ELECTRÓNICAMENTE",
      detalle: "Documento firmado electrónicamente con certificado digital válido. No se requiere clave ni secretos en auditoría.",
      badge: "FIRMADO",
      badgeColor: { bg: "#e0f2fe", text: "#0369a1", border: "#bae6fd" },
      version: "v1.0",
    },
    {
      id: "th-p-2",
      fechaHora: "06/09/2026 — 09:15",
      usuario: "Ing. Andrea Pérez, Mg.",
      rol: "Docente elaboradora",
      hito: "PLAN ENVIADO A REVISIÓN",
      detalle: "Remisión formal al comité de revisión institucional. El plan pasa al estado EN REVISIÓN.",
      badge: "EN REVISIÓN",
      badgeColor: { bg: "#fef3c7", text: "#92400e", border: "#fde68a" },
      version: "v1.0",
    },
    {
      id: "th-p-3",
      fechaHora: "06/09/2026 — 10:25",
      usuario: "Ing. Carlos López, Mg.",
      rol: "Revisor asignado",
      hito: "OBSERVACIÓN REGISTRADA",
      detalle: "Registro de observación técnica: Ajustar el cronograma y justificar horas en ponencias magistrales.",
      badge: "OBSERVADO",
      badgeColor: { bg: "#fee2e2", text: "#991b1b", border: "#fecaca" },
      version: "v1.0",
    },
    {
      id: "th-p-4",
      fechaHora: "06/09/2026 — 10:30",
      usuario: "Ing. Carlos López, Mg.",
      rol: "Revisor asignado",
      hito: "PLAN DEVUELTO",
      detalle: "Devolución del plan al docente elaborador para subsanar observaciones. Mantiene versión 1.0 (no se crea v2.0 formal por devolución).",
      badge: "DEVUELTO",
      badgeColor: { bg: "#fee2e2", text: "#991b1b", border: "#fecaca" },
      version: "v1.0",
    },
    {
      id: "th-p-5",
      fechaHora: "07/09/2026 — 08:45",
      usuario: "Ing. Andrea Pérez, Mg.",
      rol: "Docente elaboradora",
      hito: "CORRECCIÓN INICIADA",
      detalle: "La docente abre el plan devuelto para subsanar los puntos observados por el revisor.",
      badge: "EN CORRECCIÓN",
      badgeColor: { bg: "#fef3c7", text: "#b45309", border: "#fde68a" },
      version: "v1.0",
    },
  ],
};

export const TRAZABILIDAD_EVIDENCIA_ACTA: TrazabilidadObjeto = {
  id: "evidencia-acta-ut",
  tipo: "Evidencia",
  titulo: "Evidencia: Acta de reunión y constancias",
  subtitulo: "Actividad: Seguimiento al avance de trabajos de titulación • Unidad de Titulación",
  hitos: [
    {
      id: "th-e-1",
      fechaHora: "06/09/2026 — 15:20",
      usuario: "Ing. Andrea Pérez, Mg.",
      rol: "Docente responsable",
      hito: "EVIDENCIA CARGADA (v1.0)",
      detalle: "Carga del archivo PDF inicial 'Acta_Reunion_01.pdf' (1.8 MB). Estado inicial: Pendiente de validación.",
      badge: "CARGADA v1.0",
      badgeColor: { bg: "#dbeafe", text: "#1e40af", border: "#bfdbfe" },
      version: "v1.0",
    },
    {
      id: "th-e-2",
      fechaHora: "07/09/2026 — 10:25",
      usuario: "Ing. Carlos López, Mg.",
      rol: "Revisor técnico",
      hito: "EVIDENCIA OBSERVADA",
      detalle: "Observación registrada: 'Falta la firma de constancia de asistencia y sello del tutor'.",
      badge: "OBSERVADA",
      badgeColor: { bg: "#fee2e2", text: "#991b1b", border: "#fecaca" },
      version: "v1.0",
    },
    {
      id: "th-e-3",
      fechaHora: "07/09/2026 — 10:30",
      usuario: "Ing. Andrea Pérez, Mg.",
      rol: "Docente responsable",
      hito: "EVIDENCIA SUSTITUIDA / REEMPLAZADA",
      detalle: "Sustitución con nuevo archivo firmado 'Acta_Reunion_01_Firmada.pdf' (2.1 MB). Se genera v2.0.",
      badge: "REEMPLAZADA v2.0",
      badgeColor: { bg: "#fef3c7", text: "#b45309", border: "#fde68a" },
      version: "v2.0",
    },
    {
      id: "th-e-4",
      fechaHora: "07/09/2026 — 10:35",
      usuario: "Ing. Carlos López, Mg.",
      rol: "Revisor técnico",
      hito: "EVIDENCIA VALIDADA",
      detalle: "Validación técnica aprobada conforme a los medios de verificación institucional.",
      badge: "VALIDADA",
      badgeColor: { bg: "#dcfce7", text: "#166534", border: "#bbf7d0" },
      version: "v2.0",
    },
  ],
};

export const TRAZABILIDAD_USUARIO_ANDREA: TrazabilidadObjeto = {
  id: "usuario-andrea-trace",
  tipo: "Usuario",
  titulo: "Historial de acciones: Ing. Andrea Pérez, Mg.",
  subtitulo: "Rol: Docente • Departamento de Sistemas • Facultad FISEI (Solo consulta administrativa)",
  hitos: [
    {
      id: "th-u-1",
      fechaHora: "05/09/2026 — 23:41",
      usuario: "Ing. Andrea Pérez, Mg.",
      rol: "Docente",
      hito: "FIRMÓ PLAN DE TRABAJO",
      detalle: "Firma electrónica del Plan de Trabajo de la Comisión de Eventos Académicos.",
      badge: "PLAN FIRMADO",
      badgeColor: { bg: "#e0f2fe", text: "#0369a1", border: "#bae6fd" },
    },
    {
      id: "th-u-2",
      fechaHora: "06/09/2026 — 09:15",
      usuario: "Ing. Andrea Pérez, Mg.",
      rol: "Docente",
      hito: "ENVIÓ PLAN A REVISIÓN",
      detalle: "Envío formal del Plan de Trabajo v1.0 a la comisión de revisión.",
      badge: "PLAN ENVIADO",
      badgeColor: { bg: "#fef3c7", text: "#92400e", border: "#fde68a" },
    },
    {
      id: "th-u-3",
      fechaHora: "06/09/2026 — 15:20",
      usuario: "Ing. Andrea Pérez, Mg.",
      rol: "Docente",
      hito: "CARGÓ EVIDENCIA",
      detalle: "Carga de documento digital 'Acta v1.0' en Unidad de Titulación.",
      badge: "EVIDENCIA CARGADA",
      badgeColor: { bg: "#dbeafe", text: "#1e40af", border: "#bfdbfe" },
    },
    {
      id: "th-u-4",
      fechaHora: "07/09/2026 — 08:50",
      usuario: "Ing. Andrea Pérez, Mg.",
      rol: "Docente",
      hito: "INICIÓ CORRECCIÓN DE PLAN",
      detalle: "Apertura del plan devuelto para subsanar observaciones de cronograma.",
      badge: "PLAN EN CORRECCIÓN",
      badgeColor: { bg: "#fef3c7", text: "#b45309", border: "#fde68a" },
    },
    {
      id: "th-u-5",
      fechaHora: "07/09/2026 — 10:30",
      usuario: "Ing. Andrea Pérez, Mg.",
      rol: "Docente",
      hito: "REEMPLAZÓ EVIDENCIA",
      detalle: "Carga de versión corregida 'Acta v2.0' con firmas completas de tutoría.",
      badge: "EVIDENCIA REEMPLAZADA",
      badgeColor: { bg: "#dcfce7", text: "#166534", border: "#bbf7d0" },
    },
  ],
};
