interface AdminDashboardViewProps {
  onNavigate: (seccion: string) => void;
  metricas: {
    usuariosActivos: number; gruposInstitucionales: number; periodoActivo: string;
    borradores: number; enRevision: number; enCorreccion: number; validados: number; enEjecucion: number;
    evidenciasPendientes: number; evidenciasObservadas: number; evidenciasValidadas: number;
    flujosConfigurados: number; flujosPendientes: number; actividadReciente: string[];
  };
}
const Card=({title,count,color,onClick,testId}:{title:string;count:number|string;color:string;onClick?:()=>void;testId?:string})=><button data-testid={testId} onClick={onClick} style={{background:"#fff",border:"1px solid #e2e8f0",borderLeft:`4px solid ${color}`,borderRadius:9,padding:"13px 15px",textAlign:"left",cursor:onClick?"pointer":"default"}}><div style={{fontSize:22,fontWeight:800,color:"#1e2a3a"}}>{count}</div><div style={{fontSize:12,color:"#64748b",marginTop:2}}>{title}</div></button>;
export default function AdminDashboardView({onNavigate,metricas}:AdminDashboardViewProps){
 return <div data-testid="admin-dashboard" style={{padding:28,maxWidth:1240,margin:"0 auto"}}>
  <div style={{marginBottom:18}}><h1 style={{fontSize:23,color:"#1e2a3a",margin:"0 0 4px"}}>Panel General</h1><p style={{fontSize:13,color:"#64748b",margin:0}}>Estado operativo actual de Gestión Documental Académica.</p></div>
  <section aria-label="Documentos"><h2 style={{fontSize:14,color:"#1e2a3a"}}>Documentos</h2><div style={{display:"grid",gridTemplateColumns:"repeat(5,minmax(130px,1fr))",gap:10}}><Card title="Borradores" count={metricas.borradores} color="#64748b" onClick={()=>onNavigate("reportes")} testId="metric-drafts"/><Card title="En revisión" count={metricas.enRevision} color="#1a4f8a" onClick={()=>onNavigate("reportes")} testId="metric-review"/><Card title="En corrección" count={metricas.enCorreccion} color="#d97706" onClick={()=>onNavigate("reportes")}/><Card title="Validados" count={metricas.validados} color="#16a34a" onClick={()=>onNavigate("reportes")}/><Card title="En ejecución" count={metricas.enEjecucion} color="#0891b2" onClick={()=>onNavigate("reportes")}/></div></section>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:18,marginTop:18}}>
   <section style={{background:"white",border:"1px solid #e2e8f0",borderRadius:10,padding:18}}><h2 style={{fontSize:14,marginTop:0}}>Evidencias</h2><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}><Card title="Pendientes de validación" count={metricas.evidenciasPendientes} color="#d97706" onClick={()=>onNavigate("evidenciasValidar")}/><Card title="Observadas" count={metricas.evidenciasObservadas} color="#dc2626" onClick={()=>onNavigate("evidenciasValidar")}/><Card title="Validadas" count={metricas.evidenciasValidadas} color="#16a34a" onClick={()=>onNavigate("evidenciasValidar")}/></div></section>
   <section style={{background:"white",border:"1px solid #e2e8f0",borderRadius:10,padding:18}}><h2 style={{fontSize:14,marginTop:0}}>Configuración</h2><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><Card title="Flujos configurados" count={metricas.flujosConfigurados} color="#16a34a" onClick={()=>onNavigate("adminFlujos")}/><Card title="Flujos pendientes" count={metricas.flujosPendientes} color="#d97706" onClick={()=>onNavigate("adminFlujos")}/><Card title="Usuarios activos" count={metricas.usuariosActivos} color="#1a4f8a" onClick={()=>onNavigate("adminUsuarios")}/><Card title="Grupos institucionales" count={metricas.gruposInstitucionales} color="#0891b2" onClick={()=>onNavigate("adminGrupos")}/></div></section>
  </div>
  <div style={{display:"grid",gridTemplateColumns:".8fr 1.2fr",gap:18,marginTop:18}}><section style={{background:"#eff6ff",border:"1px solid #bfdbfe",borderRadius:10,padding:18}}><h2 style={{fontSize:14,marginTop:0}}>Período activo</h2><strong style={{color:"#1a4f8a"}}>{metricas.periodoActivo}</strong><p style={{fontSize:12,color:"#475569"}}>Configuración académica vigente.</p><button className="btn btn-secondary btn-sm" onClick={()=>onNavigate("adminPeriodos")}>Ver período</button></section><section style={{background:"white",border:"1px solid #e2e8f0",borderRadius:10,padding:18}}><h2 style={{fontSize:14,marginTop:0}}>Actividad documental reciente</h2>{metricas.actividadReciente.length?<ul style={{margin:0,paddingLeft:20}}>{metricas.actividadReciente.slice(0,4).map((item,i)=><li key={i} style={{fontSize:12.5,color:"#475569",padding:"4px 0"}}>{item}</li>)}</ul>:<p style={{fontSize:12,color:"#64748b"}}>Sin eventos recientes.</p>}<button className="btn btn-ghost btn-sm" onClick={()=>onNavigate("adminAuditoria")}>Abrir auditoría</button></section></div>
 </div>;
}
