import { ActividadEjecucion } from "../modulo5/types";

export const REVISOR_ACTUAL = "Ing. Carlos López, Mg.";
export const GRUPOS_ASIGNADOS_REVISOR = ["Unidad de Titulación"];

export const ACTIVIDADES_SEGUIMIENTO_INICIALES: ActividadEjecucion[] = [
  // Escenario A: Evidencia pendiente de validación (act-1, m-1-1)
  {
    id: "act-1",
    nombre: "Seguimiento al avance de trabajos de titulación",
    categoria: "POA",
    tipo: "obligatoria",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "02/09/2026",
    hasta: "18/09/2026",
    fechaLimiteExacta: "18/09/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg.", "Ing. Carlos López, Mg."],
    recursos: ["Matriz de seguimiento", "Almacenamiento institucional"],
    estado: "EN CURSO",
    medios: [
      {
        id: "m-1-1",
        nombre: "Informe",
        descripcion: "Informe técnico de avance de los proyectos de grado registrados.",
        estado: "PENDIENTE DE VALIDACIÓN",
        estadoValidacion: "PENDIENTE DE VALIDACIÓN",
        archivoVigente: {
          nombre: "informe_seguimiento_titulacion.pdf",
          tamano: "2.4 MB",
          fechaCarga: "05/09/2026 — 14:32",
          cargadoPor: "Ing. Andrea Pérez, Mg.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "informe_seguimiento_titulacion.pdf",
            tamano: "2.4 MB",
            fechaCarga: "05/09/2026 — 14:32",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: true,
            estadoRevision: "PENDIENTE DE VALIDACIÓN",
          },
        ],
        eventosAuditoria: [
          {
            id: "ev-1-1",
            tipo: "CARGA",
            titulo: "Archivo inicial cargado",
            descripcion: "Carga ordinaria del informe técnico de avance.",
            usuario: "Ing. Andrea Pérez, Mg.",
            fecha: "05/09/2026",
            hora: "14:32",
            version: 1,
          },
        ],
      },
      {
        id: "m-1-2",
        nombre: "Acta",
        descripcion: "Acta de reunión con tutores y estudiantes asignados.",
        estado: "OBSERVADA",
        estadoValidacion: "OBSERVADA",
        archivoVigente: {
          nombre: "acta_reunion_tutores_v1.pdf",
          tamano: "1.8 MB",
          fechaCarga: "06/09/2026 — 15:20",
          cargadoPor: "Ing. Andrea Pérez, Mg.",
        },
        revisionActual: {
          revisadoPor: "Ing. Carlos López, Mg.",
          fechaRevision: "07/09/2026 — 10:28",
          observacion: "Falta la firma de constancia de asistencia y sello del tutor.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "acta_reunion_tutores_v1.pdf",
            tamano: "1.8 MB",
            fechaCarga: "06/09/2026 — 15:20",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: true,
            estadoRevision: "OBSERVADA",
            fechaRevision: "07/09/2026 — 10:28",
            revisadoPor: "Ing. Carlos López, Mg.",
            observacion: "Falta la firma de constancia de asistencia y sello del tutor.",
          },
        ],
        eventosAuditoria: [
          {
            id: "ev-1-2-1",
            tipo: "CARGA",
            titulo: "Archivo inicial cargado",
            descripcion: "Carga del archivo PDF inicial 'Acta_Reunion_01.pdf' (1.8 MB).",
            usuario: "Ing. Andrea Pérez, Mg.",
            fecha: "06/09/2026",
            hora: "15:20",
            version: 1,
          },
          {
            id: "ev-1-2-2",
            tipo: "OBSERVACION",
            titulo: "Evidencia observada",
            descripcion: "Falta la firma de constancia de asistencia y sello del tutor.",
            usuario: "Ing. Carlos López, Mg.",
            fecha: "07/09/2026",
            hora: "10:28",
            version: 1,
          },
        ],
      },
    ],
  },

  // Escenario F: Plazo Vencido (act-2, m-2-1)
  {
    id: "act-2",
    nombre: "Jornada informativa para estudiantes",
    categoria: "Plan de Mejoras",
    tipo: "opcional",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "03/09/2026",
    hasta: "06/09/2026",
    fechaLimiteExacta: "06/09/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg."],
    recursos: ["Sala de reuniones", "Equipos de cómputo"],
    estado: "VENCIDA",
    medios: [
      {
        id: "m-2-1",
        nombre: "Certificado",
        descripcion: "Registro de asistencia y certificado de realización de la jornada.",
        estado: "PLAZO VENCIDO",
        historialVersiones: [],
        eventosAuditoria: [],
      },
    ],
  },

  // Escenario B: Evidencia validada (act-3, m-3-1)
  {
    id: "act-3",
    nombre: "Difusión de normativa interna de titulación",
    categoria: "Plan de Mejoras",
    tipo: "obligatoria",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "01/09/2026",
    hasta: "03/09/2026",
    fechaLimiteExacta: "03/09/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg."],
    recursos: ["Reglamento de titulación", "Correo institucional"],
    estado: "EVIDENCIAS COMPLETAS",
    medios: [
      {
        id: "m-3-1",
        nombre: "Informe",
        descripcion: "Constancia de difusión electrónica y reuniones informativas.",
        estado: "VALIDADA",
        estadoValidacion: "VALIDADA",
        archivoVigente: {
          nombre: "informe_difusion_normativa.pdf",
          tamano: "1.5 MB",
          fechaCarga: "02/09/2026 — 10:15",
          cargadoPor: "Ing. Andrea Pérez, Mg.",
        },
        revisionActual: {
          revisadoPor: "Ing. Carlos López, Mg.",
          fechaRevision: "03/09/2026 — 11:30",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "informe_difusion_normativa.pdf",
            tamano: "1.5 MB",
            fechaCarga: "02/09/2026 — 10:15",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: true,
            estadoRevision: "VALIDADA",
            revisadoPor: "Ing. Carlos López, Mg.",
            fechaRevision: "03/09/2026 — 11:30",
          },
        ],
        eventosAuditoria: [
          {
            id: "ev-3-1",
            tipo: "CARGA",
            titulo: "Archivo cargado",
            descripcion: "Evidencia subida dentro del plazo.",
            usuario: "Ing. Andrea Pérez, Mg.",
            fecha: "02/09/2026",
            hora: "10:15",
            version: 1,
          },
          {
            id: "ev-3-2",
            tipo: "VALIDACION",
            titulo: "Evidencia Validada",
            descripcion: "Documento verificado y conforme a la normativa.",
            usuario: "Ing. Carlos López, Mg.",
            fecha: "03/09/2026",
            hora: "11:30",
            version: 1,
          },
        ],
      },
    ],
  },

  // Escenario C y D: Evidencia observada (m-4-1) y Evidencia observada reemplazada (m-4-2)
  {
    id: "act-4",
    nombre: "Revisión de planes de grado cohorte 2025",
    categoria: "POA",
    tipo: "obligatoria",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "25/08/2026",
    hasta: "12/09/2026",
    fechaLimiteExacta: "12/09/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg.", "Ing. Carlos López, Mg."],
    recursos: ["Sistema de gestión académica", "Rúbricas de evaluación"],
    estado: "EN CURSO",
    medios: [
      // Escenario C: Observada
      {
        id: "m-4-1",
        nombre: "Informe",
        descripcion: "Informe de aprobación de planes de titulación evaluados.",
        estado: "OBSERVADA",
        estadoValidacion: "OBSERVADA",
        archivoVigente: {
          nombre: "informe_revision_planes_cohorte2025.pdf",
          tamano: "3.1 MB",
          fechaCarga: "03/09/2026 — 16:40",
          cargadoPor: "Ing. Andrea Pérez, Mg.",
        },
        revisionActual: {
          revisadoPor: "Ing. Carlos López, Mg.",
          fechaRevision: "04/09/2026 — 10:20",
          observacion: "El informe no incluye el consolidado de observaciones de los miembros del tribunal evaluador ni las firmas completas.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "informe_revision_planes_cohorte2025.pdf",
            tamano: "3.1 MB",
            fechaCarga: "03/09/2026 — 16:40",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: true,
            estadoRevision: "OBSERVADA",
            revisadoPor: "Ing. Carlos López, Mg.",
            fechaRevision: "04/09/2026 — 10:20",
            observacion: "El informe no incluye el consolidado de observaciones de los miembros del tribunal evaluador ni las firmas completas.",
          },
        ],
        eventosAuditoria: [
          {
            id: "ev-4-1",
            tipo: "CARGA",
            titulo: "Archivo inicial cargado",
            descripcion: "Carga de informe preliminar de evaluación.",
            usuario: "Ing. Andrea Pérez, Mg.",
            fecha: "03/09/2026",
            hora: "16:40",
            version: 1,
          },
          {
            id: "ev-4-2",
            tipo: "OBSERVACION",
            titulo: "Evidencia Observada",
            descripcion: "Se registraron observaciones de contenido formal.",
            usuario: "Ing. Carlos López, Mg.",
            fecha: "04/09/2026",
            hora: "10:20",
            version: 1,
            observacionTexto: "El informe no incluye el consolidado de observaciones de los miembros del tribunal evaluador ni las firmas completas.",
          },
        ],
      },
      // Escenario D: Observada y reemplazada (v1 observada -> v2 pendiente)
      {
        id: "m-4-2",
        nombre: "Acta",
        descripcion: "Acta de sesión de comisión de titulación.",
        estado: "PENDIENTE DE VALIDACIÓN",
        estadoValidacion: "PENDIENTE DE VALIDACIÓN",
        archivoVigente: {
          nombre: "acta_sesion_aprobacion_planes_v2.pdf",
          tamano: "1.3 MB",
          fechaCarga: "06/09/2026 — 11:20",
          cargadoPor: "Ing. Andrea Pérez, Mg.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "acta_sesion_aprobacion_planes_v1.pdf",
            tamano: "1.1 MB",
            fechaCarga: "03/09/2026 — 09:15",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: false,
            estadoRevision: "OBSERVADA",
            revisadoPor: "Ing. Carlos López, Mg.",
            fechaRevision: "04/09/2026 — 11:00",
            observacion: "El documento carece de la firma del secretario de comisión.",
            motivoReemplazo: "Se adjunta acta con firmas completas de todos los miembros.",
          },
          {
            version: 2,
            nombreArchivo: "acta_sesion_aprobacion_planes_v2.pdf",
            tamano: "1.3 MB",
            fechaCarga: "06/09/2026 — 11:20",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: true,
            estadoRevision: "PENDIENTE DE VALIDACIÓN",
          },
        ],
        eventosAuditoria: [
          {
            id: "ev-4-2-1",
            tipo: "CARGA",
            titulo: "Archivo v1 cargado",
            descripcion: "Carga inicial de acta.",
            usuario: "Ing. Andrea Pérez, Mg.",
            fecha: "03/09/2026",
            hora: "09:15",
            version: 1,
          },
          {
            id: "ev-4-2-2",
            tipo: "OBSERVACION",
            titulo: "Evidencia Observada (v1)",
            descripcion: "Falta de firma formal.",
            usuario: "Ing. Carlos López, Mg.",
            fecha: "04/09/2026",
            hora: "11:00",
            version: 1,
            observacionTexto: "El documento carece de la firma del secretario de comisión.",
          },
          {
            id: "ev-4-2-3",
            tipo: "REEMPLAZO",
            titulo: "Archivo reemplazado (v2)",
            descripcion: "Se adjunta acta con firmas completas de todos los miembros.",
            usuario: "Ing. Andrea Pérez, Mg.",
            fecha: "06/09/2026",
            hora: "11:20",
            version: 2,
          },
        ],
      },
    ],
  },

  // Escenario E: Validada y posteriormente reemplazada dentro del plazo (m-6-1)
  {
    id: "act-6",
    nombre: "Taller de inducción metodológica para tutores",
    categoria: "Plan de Mejoras",
    tipo: "obligatoria",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "25/08/2026",
    hasta: "15/09/2026",
    fechaLimiteExacta: "15/09/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg."],
    recursos: ["Sala de conferencias", "Material didáctico"],
    estado: "EN CURSO",
    medios: [
      {
        id: "m-6-1",
        nombre: "Informe",
        descripcion: "Memoria del taller y consolidado de retroalimentación docente.",
        estado: "PENDIENTE DE VALIDACIÓN",
        estadoValidacion: "PENDIENTE DE VALIDACIÓN",
        archivoVigente: {
          nombre: "memoria_taller_tutores_actualizada.pdf",
          tamano: "2.3 MB",
          fechaCarga: "06/09/2026 — 17:00",
          cargadoPor: "Ing. Andrea Pérez, Mg.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "memoria_taller_tutores.pdf",
            tamano: "2.1 MB",
            fechaCarga: "01/09/2026 — 10:00",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: false,
            estadoRevision: "VALIDADA",
            revisadoPor: "Ing. Carlos López, Mg.",
            fechaRevision: "02/09/2026 — 15:30",
            motivoReemplazo: "Inclusión de lista complementaria de asistencia de tutores virtuales.",
          },
          {
            version: 2,
            nombreArchivo: "memoria_taller_tutores_actualizada.pdf",
            tamano: "2.3 MB",
            fechaCarga: "06/09/2026 — 17:00",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: true,
            estadoRevision: "PENDIENTE DE VALIDACIÓN",
          },
        ],
        eventosAuditoria: [
          {
            id: "ev-6-1",
            tipo: "CARGA",
            titulo: "Archivo inicial v1 cargado",
            descripcion: "Memoria del evento presencial.",
            usuario: "Ing. Andrea Pérez, Mg.",
            fecha: "01/09/2026",
            hora: "10:00",
            version: 1,
          },
          {
            id: "ev-6-2",
            tipo: "VALIDACION",
            titulo: "Evidencia Validada (v1)",
            descripcion: "Aprobada por el revisor institucional.",
            usuario: "Ing. Carlos López, Mg.",
            fecha: "02/09/2026",
            hora: "15:30",
            version: 1,
          },
          {
            id: "ev-6-3",
            tipo: "REEMPLAZO",
            titulo: "Archivo reemplazado (v2)",
            descripcion: "Inclusión de lista complementaria de asistencia de tutores virtuales. Pasa a pendiente de re-validación.",
            usuario: "Ing. Andrea Pérez, Mg.",
            fecha: "06/09/2026",
            hora: "17:00",
            version: 2,
          },
        ],
      },
      {
        id: "m-6-2",
        nombre: "Registro fotográfico",
        descripcion: "Evidencia visual del desarrollo del taller presencial.",
        estado: "VALIDADA",
        estadoValidacion: "VALIDADA",
        archivoVigente: {
          nombre: "registro_fotografico_taller.pdf",
          tamano: "4.5 MB",
          fechaCarga: "01/09/2026 — 12:30",
          cargadoPor: "Ing. Andrea Pérez, Mg.",
        },
        revisionActual: {
          revisadoPor: "Ing. Carlos López, Mg.",
          fechaRevision: "02/09/2026 — 15:40",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "registro_fotografico_taller.pdf",
            tamano: "4.5 MB",
            fechaCarga: "01/09/2026 — 12:30",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: true,
            estadoRevision: "VALIDADA",
            revisadoPor: "Ing. Carlos López, Mg.",
            fechaRevision: "02/09/2026 — 15:40",
          },
        ],
        eventosAuditoria: [
          {
            id: "ev-6-2-1",
            tipo: "CARGA",
            titulo: "Archivo cargado",
            descripcion: "Registro fotográfico del taller.",
            usuario: "Ing. Andrea Pérez, Mg.",
            fecha: "01/09/2026",
            hora: "12:30",
            version: 1,
          },
          {
            id: "ev-6-2-2",
            tipo: "VALIDACION",
            titulo: "Evidencia Validada",
            descripcion: "Registro visual verificado.",
            usuario: "Ing. Carlos López, Mg.",
            fecha: "02/09/2026",
            hora: "15:40",
            version: 1,
          },
        ],
      },
    ],
  },

  // Escenario G: Actividad con dos medios: 2 cargados, pero 1 validado y 1 pendiente (RN-13)
  {
    id: "act-9",
    nombre: "Seguimiento de procesos de graduación",
    categoria: "Acción de Mejora",
    tipo: "opcional",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "01/09/2026",
    hasta: "25/09/2026",
    fechaLimiteExacta: "25/09/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg.", "Ing. Carlos López, Mg."],
    recursos: ["Sistema de gestión académica", "Expedientes estudiantiles"],
    estado: "EVIDENCIAS COMPLETAS", // 2/2 medios cargados
    medios: [
      {
        id: "m-9-1",
        nombre: "Informe",
        descripcion: "Estado de carpetas de titulación y prerrequisitos de graduación.",
        estado: "VALIDADA",
        estadoValidacion: "VALIDADA",
        archivoVigente: {
          nombre: "informe_tramites_graduacion.pdf",
          tamano: "1.9 MB",
          fechaCarga: "05/09/2026 — 16:20",
          cargadoPor: "Ing. Carlos López, Mg.",
        },
        revisionActual: {
          revisadoPor: "Ing. Carlos López, Mg.",
          fechaRevision: "06/09/2026 — 09:30",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "informe_tramites_graduacion.pdf",
            tamano: "1.9 MB",
            fechaCarga: "05/09/2026 — 16:20",
            cargadoPor: "Ing. Carlos López, Mg.",
            vigente: true,
            estadoRevision: "VALIDADA",
            revisadoPor: "Ing. Carlos López, Mg.",
            fechaRevision: "06/09/2026 — 09:30",
          },
        ],
        eventosAuditoria: [
          {
            id: "ev-9-1",
            tipo: "CARGA",
            titulo: "Archivo cargado",
            descripcion: "Informe de prerrequisitos de graduación.",
            usuario: "Ing. Carlos López, Mg.",
            fecha: "05/09/2026",
            hora: "16:20",
            version: 1,
          },
          {
            id: "ev-9-2",
            tipo: "VALIDACION",
            titulo: "Evidencia Validada",
            descripcion: "Verificación de carpetas concluida.",
            usuario: "Ing. Carlos López, Mg.",
            fecha: "06/09/2026",
            hora: "09:30",
            version: 1,
          },
        ],
      },
      {
        id: "m-9-2",
        nombre: "Acta",
        descripcion: "Acta de validación de expedientes de titulación.",
        estado: "PENDIENTE DE VALIDACIÓN", // Cargada pero NO validada
        estadoValidacion: "PENDIENTE DE VALIDACIÓN",
        archivoVigente: {
          nombre: "acta_validacion_expedientes.pdf",
          tamano: "1.4 MB",
          fechaCarga: "06/09/2026 — 15:45",
          cargadoPor: "Ing. Andrea Pérez, Mg.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "acta_validacion_expedientes.pdf",
            tamano: "1.4 MB",
            fechaCarga: "06/09/2026 — 15:45",
            cargadoPor: "Ing. Andrea Pérez, Mg.",
            vigente: true,
            estadoRevision: "PENDIENTE DE VALIDACIÓN",
          },
        ],
        eventosAuditoria: [
          {
            id: "ev-9-3",
            tipo: "CARGA",
            titulo: "Archivo cargado",
            descripcion: "Acta de validación remitida por el docente.",
            usuario: "Ing. Andrea Pérez, Mg.",
            fecha: "06/09/2026",
            hora: "15:45",
            version: 1,
          },
        ],
      },
    ],
  },

  // Escenario H: Actividad donde Andrea NO es responsable (act-11, responsable: Carlos)
  {
    id: "act-11",
    nombre: "Revisión de documentación de titulación",
    categoria: "POA",
    tipo: "obligatoria",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "01/09/2026",
    hasta: "22/09/2026",
    fechaLimiteExacta: "22/09/2026 — 23:59",
    responsables: ["Ing. Carlos López, Mg."],
    recursos: ["Expedientes estudiantiles", "Reglamento de graduación"],
    estado: "EN CURSO",
    medios: [
      {
        id: "m-11-1",
        nombre: "Informe",
        descripcion: "Informe técnico de revisión y validación de expedientes de grado.",
        estado: "PENDIENTE DE VALIDACIÓN",
        estadoValidacion: "PENDIENTE DE VALIDACIÓN",
        archivoVigente: {
          nombre: "informe_revision_titulacion_carlos.pdf",
          tamano: "2.7 MB",
          fechaCarga: "06/09/2026 — 18:10",
          cargadoPor: "Ing. Carlos López, Mg.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "informe_revision_titulacion_carlos.pdf",
            tamano: "2.7 MB",
            fechaCarga: "06/09/2026 — 18:10",
            cargadoPor: "Ing. Carlos López, Mg.",
            vigente: true,
            estadoRevision: "PENDIENTE DE VALIDACIÓN",
          },
        ],
        eventosAuditoria: [
          {
            id: "ev-11-1",
            tipo: "CARGA",
            titulo: "Archivo cargado",
            descripcion: "Carga de informe de titulación por el docente responsable.",
            usuario: "Ing. Carlos López, Mg.",
            fecha: "06/09/2026",
            hora: "18:10",
            version: 1,
          },
        ],
      },
    ],
  },

  // Escenario I: Actividad perteneciente a un grupo NO asignado a Carlos López (RN-11)
  {
    id: "act-12",
    nombre: "Taller de transferencia tecnológica comunitaria",
    categoria: "POA",
    tipo: "obligatoria",
    planNombre: "Plan de Trabajo — Vinculación con la Sociedad",
    grupo: "Comisión de Vinculación", // Carlos NO tiene este grupo asignado
    periodo: "Julio – Diciembre 2026",
    desde: "01/09/2026",
    hasta: "28/09/2026",
    fechaLimiteExacta: "28/09/2026 — 23:59",
    responsables: ["Dr. Fernando Ramos, PhD."],
    recursos: ["Laboratorio móvil", "Guías comunitarias"],
    estado: "EN CURSO",
    medios: [
      {
        id: "m-12-1",
        nombre: "Informe",
        descripcion: "Memoria del taller tecnológico con la comunidad de Izamba.",
        estado: "PENDIENTE DE VALIDACIÓN",
        estadoValidacion: "PENDIENTE DE VALIDACIÓN",
        archivoVigente: {
          nombre: "memoria_vinculacion_comunitaria.pdf",
          tamano: "3.5 MB",
          fechaCarga: "05/09/2026 — 12:00",
          cargadoPor: "Dr. Fernando Ramos, PhD.",
        },
        historialVersiones: [
          {
            version: 1,
            nombreArchivo: "memoria_vinculacion_comunitaria.pdf",
            tamano: "3.5 MB",
            fechaCarga: "05/09/2026 — 12:00",
            cargadoPor: "Dr. Fernando Ramos, PhD.",
            vigente: true,
            estadoRevision: "PENDIENTE DE VALIDACIÓN",
          },
        ],
        eventosAuditoria: [
          {
            id: "ev-12-1",
            tipo: "CARGA",
            titulo: "Archivo cargado",
            descripcion: "Memoria de vinculación.",
            usuario: "Dr. Fernando Ramos, PhD.",
            fecha: "05/09/2026",
            hora: "12:00",
            version: 1,
          },
        ],
      },
    ],
  },

  // Escenario J: Actividad próxima a vencer en 5 días (vence 12/09/2026 para FECHA_SISTEMA = 07/09/2026)
  {
    id: "act-13",
    nombre: "Presentación de informes mensuales de comisiones",
    categoria: "POA",
    tipo: "obligatoria",
    planNombre: "Plan de Trabajo — Unidad de Titulación",
    grupo: "Unidad de Titulación",
    periodo: "Julio – Diciembre 2026",
    desde: "01/09/2026",
    hasta: "12/09/2026",
    fechaLimiteExacta: "12/09/2026 — 23:59",
    responsables: ["Ing. Andrea Pérez, Mg."],
    recursos: ["Plantillas institucionales FISEI"],
    estado: "EN CURSO",
    medios: [
      {
        id: "m-13-1",
        nombre: "Informe mensual",
        descripcion: "Informe de avance mensual correspondiente a la comisión.",
        estado: "PENDIENTE",
        historialVersiones: [],
        eventosAuditoria: [],
      },
    ],
  },
];
